// Code generated by MockGen. DO NOT EDIT.
// Source: borrows.go
//
// Generated by this command:
//
//	mockgen -source=borrows.go -destination=./mock/mock_transaction_repository.go -package=mock_domain
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	domain "github.com/traPtitech/booQ-v3/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTransactionRepository) Create(transaction *domain.Transaction) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", transaction)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTransactionRepositoryMockRecorder) Create(transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransactionRepository)(nil).Create), transaction)
}

// GetByID mocks base method.
func (m *MockTransactionRepository) GetByID(id int) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTransactionRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTransactionRepository)(nil).GetByID), id)
}

// GetByOwnershipID mocks base method.
func (m *MockTransactionRepository) GetByOwnershipID(ownershipID int) ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwnershipID", ownershipID)
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOwnershipID indicates an expected call of GetByOwnershipID.
func (mr *MockTransactionRepositoryMockRecorder) GetByOwnershipID(ownershipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwnershipID", reflect.TypeOf((*MockTransactionRepository)(nil).GetByOwnershipID), ownershipID)
}

// GetByUserID mocks base method.
func (m *MockTransactionRepository) GetByUserID(userID string) ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockTransactionRepositoryMockRecorder) GetByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockTransactionRepository)(nil).GetByUserID), userID)
}

// Update mocks base method.
func (m *MockTransactionRepository) Update(transaction *domain.Transaction) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", transaction)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTransactionRepositoryMockRecorder) Update(transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTransactionRepository)(nil).Update), transaction)
}

// MockEquipmentTransactionRepository is a mock of EquipmentTransactionRepository interface.
type MockEquipmentTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEquipmentTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockEquipmentTransactionRepositoryMockRecorder is the mock recorder for MockEquipmentTransactionRepository.
type MockEquipmentTransactionRepositoryMockRecorder struct {
	mock *MockEquipmentTransactionRepository
}

// NewMockEquipmentTransactionRepository creates a new mock instance.
func NewMockEquipmentTransactionRepository(ctrl *gomock.Controller) *MockEquipmentTransactionRepository {
	mock := &MockEquipmentTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockEquipmentTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEquipmentTransactionRepository) EXPECT() *MockEquipmentTransactionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEquipmentTransactionRepository) Create(transaction *domain.EquipmentTransaction) (*domain.EquipmentTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", transaction)
	ret0, _ := ret[0].(*domain.EquipmentTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEquipmentTransactionRepositoryMockRecorder) Create(transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEquipmentTransactionRepository)(nil).Create), transaction)
}

// GetByID mocks base method.
func (m *MockEquipmentTransactionRepository) GetByID(id int) (*domain.EquipmentTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.EquipmentTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEquipmentTransactionRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEquipmentTransactionRepository)(nil).GetByID), id)
}

// GetByItemID mocks base method.
func (m *MockEquipmentTransactionRepository) GetByItemID(itemID int) ([]*domain.EquipmentTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByItemID", itemID)
	ret0, _ := ret[0].([]*domain.EquipmentTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByItemID indicates an expected call of GetByItemID.
func (mr *MockEquipmentTransactionRepositoryMockRecorder) GetByItemID(itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByItemID", reflect.TypeOf((*MockEquipmentTransactionRepository)(nil).GetByItemID), itemID)
}

// GetByUserID mocks base method.
func (m *MockEquipmentTransactionRepository) GetByUserID(userID string) ([]*domain.EquipmentTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].([]*domain.EquipmentTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockEquipmentTransactionRepositoryMockRecorder) GetByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockEquipmentTransactionRepository)(nil).GetByUserID), userID)
}

// Update mocks base method.
func (m *MockEquipmentTransactionRepository) Update(transaction *domain.EquipmentTransaction) (*domain.EquipmentTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", transaction)
	ret0, _ := ret[0].(*domain.EquipmentTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEquipmentTransactionRepositoryMockRecorder) Update(transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEquipmentTransactionRepository)(nil).Update), transaction)
}
