services:
  db:
    image: mariadb:11.5.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: booq-v3
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
    volumes:
      - booq-db:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - '3306'
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  booq-server:
    build: .
    environment:
      BOOQ_ENV: development
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: booq-v3
      UPLOAD_DIR: /app/data
    ports:
      - '8080:3001'
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - path: ./Dockerfile
          action: rebuild
        - path: ./go.mod
          action: rebuild
        - path: ./main.go
          action: rebuild
        - path: ./model
          action: rebuild
        - path: ./router
          action: rebuild
        - path: ./storage
          action: rebuild
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

volumes:
  booq-db:
