// Code generated by MockGen. DO NOT EDIT.
// Source: like.go
//
// Generated by this command:
//
//	mockgen -source=like.go -destination=./mock/mock_like_repository.go -package=mock_domain
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	domain "github.com/traPtitech/booQ-v3/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLikeRepository is a mock of LikeRepository interface.
type MockLikeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLikeRepositoryMockRecorder
	isgomock struct{}
}

// MockLikeRepositoryMockRecorder is the mock recorder for MockLikeRepository.
type MockLikeRepositoryMockRecorder struct {
	mock *MockLikeRepository
}

// NewMockLikeRepository creates a new mock instance.
func NewMockLikeRepository(ctrl *gomock.Controller) *MockLikeRepository {
	mock := &MockLikeRepository{ctrl: ctrl}
	mock.recorder = &MockLikeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeRepository) EXPECT() *MockLikeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLikeRepository) Create(like *domain.Like) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", like)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLikeRepositoryMockRecorder) Create(like any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLikeRepository)(nil).Create), like)
}

// Delete mocks base method.
func (m *MockLikeRepository) Delete(itemID int, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", itemID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLikeRepositoryMockRecorder) Delete(itemID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLikeRepository)(nil).Delete), itemID, userID)
}

// Exists mocks base method.
func (m *MockLikeRepository) Exists(itemID int, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", itemID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockLikeRepositoryMockRecorder) Exists(itemID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockLikeRepository)(nil).Exists), itemID, userID)
}

// GetByItemID mocks base method.
func (m *MockLikeRepository) GetByItemID(itemID int) ([]*domain.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByItemID", itemID)
	ret0, _ := ret[0].([]*domain.Like)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByItemID indicates an expected call of GetByItemID.
func (mr *MockLikeRepositoryMockRecorder) GetByItemID(itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByItemID", reflect.TypeOf((*MockLikeRepository)(nil).GetByItemID), itemID)
}
