// Code generated by MockGen. DO NOT EDIT.
// Source: ownership.go
//
// Generated by this command:
//
//	mockgen -source=ownership.go -destination=./mock/mock_ownership_repository.go -package=mock_domain
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	domain "github.com/traPtitech/booQ-v3/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOwnershipRepository is a mock of OwnershipRepository interface.
type MockOwnershipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOwnershipRepositoryMockRecorder
	isgomock struct{}
}

// MockOwnershipRepositoryMockRecorder is the mock recorder for MockOwnershipRepository.
type MockOwnershipRepositoryMockRecorder struct {
	mock *MockOwnershipRepository
}

// NewMockOwnershipRepository creates a new mock instance.
func NewMockOwnershipRepository(ctrl *gomock.Controller) *MockOwnershipRepository {
	mock := &MockOwnershipRepository{ctrl: ctrl}
	mock.recorder = &MockOwnershipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOwnershipRepository) EXPECT() *MockOwnershipRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOwnershipRepository) Create(ownership *domain.Ownership) (*domain.Ownership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ownership)
	ret0, _ := ret[0].(*domain.Ownership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOwnershipRepositoryMockRecorder) Create(ownership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOwnershipRepository)(nil).Create), ownership)
}

// Delete mocks base method.
func (m *MockOwnershipRepository) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOwnershipRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOwnershipRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockOwnershipRepository) GetByID(id int) (*domain.Ownership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.Ownership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOwnershipRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOwnershipRepository)(nil).GetByID), id)
}

// GetByItemID mocks base method.
func (m *MockOwnershipRepository) GetByItemID(itemID int) ([]*domain.Ownership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByItemID", itemID)
	ret0, _ := ret[0].([]*domain.Ownership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByItemID indicates an expected call of GetByItemID.
func (mr *MockOwnershipRepositoryMockRecorder) GetByItemID(itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByItemID", reflect.TypeOf((*MockOwnershipRepository)(nil).GetByItemID), itemID)
}

// GetByUserID mocks base method.
func (m *MockOwnershipRepository) GetByUserID(userID string) ([]*domain.Ownership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].([]*domain.Ownership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockOwnershipRepositoryMockRecorder) GetByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockOwnershipRepository)(nil).GetByUserID), userID)
}

// Update mocks base method.
func (m *MockOwnershipRepository) Update(ownership *domain.Ownership) (*domain.Ownership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ownership)
	ret0, _ := ret[0].(*domain.Ownership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockOwnershipRepositoryMockRecorder) Update(ownership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOwnershipRepository)(nil).Update), ownership)
}
