// Code generated by MockGen. DO NOT EDIT.
// Source: tag.go
//
// Generated by this command:
//
//	mockgen -source=tag.go -destination=./mock/mock_tag_repository.go -package=mock_domain
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	domain "github.com/traPtitech/booQ-v3/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTagRepository is a mock of TagRepository interface.
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
	isgomock struct{}
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository.
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance.
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// GetByItemID mocks base method.
func (m *MockTagRepository) GetByItemID(itemID int) ([]*domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByItemID", itemID)
	ret0, _ := ret[0].([]*domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByItemID indicates an expected call of GetByItemID.
func (mr *MockTagRepositoryMockRecorder) GetByItemID(itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByItemID", reflect.TypeOf((*MockTagRepository)(nil).GetByItemID), itemID)
}

// GetByItemIDs mocks base method.
func (m *MockTagRepository) GetByItemIDs(itemIDs []int) (map[int][]*domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByItemIDs", itemIDs)
	ret0, _ := ret[0].(map[int][]*domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByItemIDs indicates an expected call of GetByItemIDs.
func (mr *MockTagRepositoryMockRecorder) GetByItemIDs(itemIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByItemIDs", reflect.TypeOf((*MockTagRepository)(nil).GetByItemIDs), itemIDs)
}

// ReplaceByItemID mocks base method.
func (m *MockTagRepository) ReplaceByItemID(itemID int, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceByItemID", itemID, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceByItemID indicates an expected call of ReplaceByItemID.
func (mr *MockTagRepositoryMockRecorder) ReplaceByItemID(itemID, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceByItemID", reflect.TypeOf((*MockTagRepository)(nil).ReplaceByItemID), itemID, tags)
}
