// Code generated by MockGen. DO NOT EDIT.
// Source: file.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	io "io"
	reflect "reflect"

	domain "github.com/traPtitech/booQ-v3/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFileUseCase is a mock of FileUseCase interface.
type MockFileUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFileUseCaseMockRecorder
}

// MockFileUseCaseMockRecorder is the mock recorder for MockFileUseCase.
type MockFileUseCaseMockRecorder struct {
	mock *MockFileUseCase
}

// NewMockFileUseCase creates a new mock instance.
func NewMockFileUseCase(ctrl *gomock.Controller) *MockFileUseCase {
	mock := &MockFileUseCase{ctrl: ctrl}
	mock.recorder = &MockFileUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileUseCase) EXPECT() *MockFileUseCaseMockRecorder {
	return m.recorder
}

// GetFile mocks base method.
func (m *MockFileUseCase) GetFile(id int) (io.ReadCloser, *domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", id)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(*domain.File)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFile indicates an expected call of GetFile.
func (mr *MockFileUseCaseMockRecorder) GetFile(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockFileUseCase)(nil).GetFile), id)
}

// Upload mocks base method.
func (m *MockFileUseCase) Upload(src io.Reader, contentType string, size int64) (*domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", src, contentType, size)
	ret0, _ := ret[0].(*domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockFileUseCaseMockRecorder) Upload(src, contentType, size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFileUseCase)(nil).Upload), src, contentType, size)
}
