// Code generated by MockGen. DO NOT EDIT.
// Source: item.go
//
// Generated by this command:
//
//	mockgen -source=item.go -destination=./mock/mock_item_usecase.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	domain "github.com/traPtitech/booQ-v3/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockItemUseCase is a mock of ItemUseCase interface.
type MockItemUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockItemUseCaseMockRecorder
	isgomock struct{}
}

// MockItemUseCaseMockRecorder is the mock recorder for MockItemUseCase.
type MockItemUseCaseMockRecorder struct {
	mock *MockItemUseCase
}

// NewMockItemUseCase creates a new mock instance.
func NewMockItemUseCase(ctrl *gomock.Controller) *MockItemUseCase {
	mock := &MockItemUseCase{ctrl: ctrl}
	mock.recorder = &MockItemUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemUseCase) EXPECT() *MockItemUseCaseMockRecorder {
	return m.recorder
}

// GetItemByID mocks base method.
func (m *MockItemUseCase) GetItemByID(id int) (*domain.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByID", id)
	ret0, _ := ret[0].(*domain.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByID indicates an expected call of GetItemByID.
func (mr *MockItemUseCaseMockRecorder) GetItemByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByID", reflect.TypeOf((*MockItemUseCase)(nil).GetItemByID), id)
}
