// Code generated by MockGen. DO NOT EDIT.
// Source: like.go
//
// Generated by this command:
//
//	mockgen -source=like.go -destination=./mock/mock_like_usecase.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	domain "github.com/traPtitech/booQ-v3/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLikeUseCase is a mock of LikeUseCase interface.
type MockLikeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockLikeUseCaseMockRecorder
	isgomock struct{}
}

// MockLikeUseCaseMockRecorder is the mock recorder for MockLikeUseCase.
type MockLikeUseCaseMockRecorder struct {
	mock *MockLikeUseCase
}

// NewMockLikeUseCase creates a new mock instance.
func NewMockLikeUseCase(ctrl *gomock.Controller) *MockLikeUseCase {
	mock := &MockLikeUseCase{ctrl: ctrl}
	mock.recorder = &MockLikeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeUseCase) EXPECT() *MockLikeUseCaseMockRecorder {
	return m.recorder
}

// AddLike mocks base method.
func (m *MockLikeUseCase) AddLike(itemID int, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLike", itemID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLike indicates an expected call of AddLike.
func (mr *MockLikeUseCaseMockRecorder) AddLike(itemID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLike", reflect.TypeOf((*MockLikeUseCase)(nil).AddLike), itemID, userID)
}

// GetByItemID mocks base method.
func (m *MockLikeUseCase) GetByItemID(itemID int) ([]*domain.Like, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByItemID", itemID)
	ret0, _ := ret[0].([]*domain.Like)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByItemID indicates an expected call of GetByItemID.
func (mr *MockLikeUseCaseMockRecorder) GetByItemID(itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByItemID", reflect.TypeOf((*MockLikeUseCase)(nil).GetByItemID), itemID)
}

// IsLiked mocks base method.
func (m *MockLikeUseCase) IsLiked(itemID int, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLiked", itemID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLiked indicates an expected call of IsLiked.
func (mr *MockLikeUseCaseMockRecorder) IsLiked(itemID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLiked", reflect.TypeOf((*MockLikeUseCase)(nil).IsLiked), itemID, userID)
}

// RemoveLike mocks base method.
func (m *MockLikeUseCase) RemoveLike(itemID int, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLike", itemID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLike indicates an expected call of RemoveLike.
func (mr *MockLikeUseCaseMockRecorder) RemoveLike(itemID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLike", reflect.TypeOf((*MockLikeUseCase)(nil).RemoveLike), itemID, userID)
}
