// Code generated by MockGen. DO NOT EDIT.
// Source: tag.go
//
// Generated by this command:
//
//	mockgen -source=tag.go -destination=./mock/mock_tag_usecase.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	domain "github.com/traPtitech/booQ-v3/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTagUseCase is a mock of TagUseCase interface.
type MockTagUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTagUseCaseMockRecorder
	isgomock struct{}
}

// MockTagUseCaseMockRecorder is the mock recorder for MockTagUseCase.
type MockTagUseCaseMockRecorder struct {
	mock *MockTagUseCase
}

// NewMockTagUseCase creates a new mock instance.
func NewMockTagUseCase(ctrl *gomock.Controller) *MockTagUseCase {
	mock := &MockTagUseCase{ctrl: ctrl}
	mock.recorder = &MockTagUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagUseCase) EXPECT() *MockTagUseCaseMockRecorder {
	return m.recorder
}

// GetByItemID mocks base method.
func (m *MockTagUseCase) GetByItemID(itemID int) ([]*domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByItemID", itemID)
	ret0, _ := ret[0].([]*domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByItemID indicates an expected call of GetByItemID.
func (mr *MockTagUseCaseMockRecorder) GetByItemID(itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByItemID", reflect.TypeOf((*MockTagUseCase)(nil).GetByItemID), itemID)
}

// ReplaceByItemID mocks base method.
func (m *MockTagUseCase) ReplaceByItemID(itemID int, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceByItemID", itemID, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceByItemID indicates an expected call of ReplaceByItemID.
func (mr *MockTagUseCaseMockRecorder) ReplaceByItemID(itemID, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceByItemID", reflect.TypeOf((*MockTagUseCase)(nil).ReplaceByItemID), itemID, tags)
}
