// Code generated by MockGen. DO NOT EDIT.
// Source: ownership.go
//
// Generated by this command:
//
//	mockgen -source=ownership.go -destination=./mock/mock_ownership_usecase.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	domain "github.com/traPtitech/booQ-v3/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOwnershipUseCase is a mock of OwnershipUseCase interface.
type MockOwnershipUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockOwnershipUseCaseMockRecorder
	isgomock struct{}
}

// MockOwnershipUseCaseMockRecorder is the mock recorder for MockOwnershipUseCase.
type MockOwnershipUseCaseMockRecorder struct {
	mock *MockOwnershipUseCase
}

// NewMockOwnershipUseCase creates a new mock instance.
func NewMockOwnershipUseCase(ctrl *gomock.Controller) *MockOwnershipUseCase {
	mock := &MockOwnershipUseCase{ctrl: ctrl}
	mock.recorder = &MockOwnershipUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOwnershipUseCase) EXPECT() *MockOwnershipUseCaseMockRecorder {
	return m.recorder
}

// CreateOwnership mocks base method.
func (m *MockOwnershipUseCase) CreateOwnership(ownership *domain.Ownership) (*domain.Ownership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOwnership", ownership)
	ret0, _ := ret[0].(*domain.Ownership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOwnership indicates an expected call of CreateOwnership.
func (mr *MockOwnershipUseCaseMockRecorder) CreateOwnership(ownership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOwnership", reflect.TypeOf((*MockOwnershipUseCase)(nil).CreateOwnership), ownership)
}

// DeleteOwnership mocks base method.
func (m *MockOwnershipUseCase) DeleteOwnership(id, itemID int, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOwnership", id, itemID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOwnership indicates an expected call of DeleteOwnership.
func (mr *MockOwnershipUseCaseMockRecorder) DeleteOwnership(id, itemID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOwnership", reflect.TypeOf((*MockOwnershipUseCase)(nil).DeleteOwnership), id, itemID, userID)
}

// GetByItemID mocks base method.
func (m *MockOwnershipUseCase) GetByItemID(itemID int) ([]*domain.Ownership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByItemID", itemID)
	ret0, _ := ret[0].([]*domain.Ownership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByItemID indicates an expected call of GetByItemID.
func (mr *MockOwnershipUseCaseMockRecorder) GetByItemID(itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByItemID", reflect.TypeOf((*MockOwnershipUseCase)(nil).GetByItemID), itemID)
}

// UpdateOwnership mocks base method.
func (m *MockOwnershipUseCase) UpdateOwnership(ownership *domain.Ownership, itemID int, userID string) (*domain.Ownership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOwnership", ownership, itemID, userID)
	ret0, _ := ret[0].(*domain.Ownership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOwnership indicates an expected call of UpdateOwnership.
func (mr *MockOwnershipUseCaseMockRecorder) UpdateOwnership(ownership, itemID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOwnership", reflect.TypeOf((*MockOwnershipUseCase)(nil).UpdateOwnership), ownership, itemID, userID)
}
