// Code generated by MockGen. DO NOT EDIT.
// Source: borrows.go
//
// Generated by this command:
//
//	mockgen -source=borrows.go -destination=./mock/mock_borrowing_usecase.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"
	time "time"

	domain "github.com/traPtitech/booQ-v3/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockBorrowingUseCase is a mock of BorrowingUseCase interface.
type MockBorrowingUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockBorrowingUseCaseMockRecorder
	isgomock struct{}
}

// MockBorrowingUseCaseMockRecorder is the mock recorder for MockBorrowingUseCase.
type MockBorrowingUseCaseMockRecorder struct {
	mock *MockBorrowingUseCase
}

// NewMockBorrowingUseCase creates a new mock instance.
func NewMockBorrowingUseCase(ctrl *gomock.Controller) *MockBorrowingUseCase {
	mock := &MockBorrowingUseCase{ctrl: ctrl}
	mock.recorder = &MockBorrowingUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBorrowingUseCase) EXPECT() *MockBorrowingUseCaseMockRecorder {
	return m.recorder
}

// GetRequest mocks base method.
func (m *MockBorrowingUseCase) GetRequest(itemID int, userID string, ownershipID, borrowingID int) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequest", itemID, userID, ownershipID, borrowingID)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequest indicates an expected call of GetRequest.
func (mr *MockBorrowingUseCaseMockRecorder) GetRequest(itemID, userID, ownershipID, borrowingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequest", reflect.TypeOf((*MockBorrowingUseCase)(nil).GetRequest), itemID, userID, ownershipID, borrowingID)
}

// PostRequest mocks base method.
func (m *MockBorrowingUseCase) PostRequest(itemID int, userID string, ownershipID int, purpose string, dueDate time.Time, borrowInClubRoom bool) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostRequest", itemID, userID, ownershipID, purpose, dueDate, borrowInClubRoom)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostRequest indicates an expected call of PostRequest.
func (mr *MockBorrowingUseCaseMockRecorder) PostRequest(itemID, userID, ownershipID, purpose, dueDate, borrowInClubRoom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostRequest", reflect.TypeOf((*MockBorrowingUseCase)(nil).PostRequest), itemID, userID, ownershipID, purpose, dueDate, borrowInClubRoom)
}

// ReplyRequest mocks base method.
func (m *MockBorrowingUseCase) ReplyRequest(itemID int, userID string, ownershipID, borrowingID int, approve bool, message string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplyRequest", itemID, userID, ownershipID, borrowingID, approve, message)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplyRequest indicates an expected call of ReplyRequest.
func (mr *MockBorrowingUseCaseMockRecorder) ReplyRequest(itemID, userID, ownershipID, borrowingID, approve, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplyRequest", reflect.TypeOf((*MockBorrowingUseCase)(nil).ReplyRequest), itemID, userID, ownershipID, borrowingID, approve, message)
}

// ReturnItem mocks base method.
func (m *MockBorrowingUseCase) ReturnItem(itemID int, userID string, ownershipID, borrowingID int, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReturnItem", itemID, userID, ownershipID, borrowingID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReturnItem indicates an expected call of ReturnItem.
func (mr *MockBorrowingUseCaseMockRecorder) ReturnItem(itemID, userID, ownershipID, borrowingID, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReturnItem", reflect.TypeOf((*MockBorrowingUseCase)(nil).ReturnItem), itemID, userID, ownershipID, borrowingID, message)
}
