// Code generated by MockGen. DO NOT EDIT.
// Source: item.go
//
// Generated by this command:
//
//	mockgen -source=item.go -destination=./mock/mock_item_usecase.go -package=mock_usecase
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	domain "github.com/traPtitech/booQ-v3/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockItemUseCase is a mock of ItemUseCase interface.
type MockItemUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockItemUseCaseMockRecorder
	isgomock struct{}
}

// MockItemUseCaseMockRecorder is the mock recorder for MockItemUseCase.
type MockItemUseCaseMockRecorder struct {
	mock *MockItemUseCase
}

// NewMockItemUseCase creates a new mock instance.
func NewMockItemUseCase(ctrl *gomock.Controller) *MockItemUseCase {
	mock := &MockItemUseCase{ctrl: ctrl}
	mock.recorder = &MockItemUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemUseCase) EXPECT() *MockItemUseCaseMockRecorder {
	return m.recorder
}

// CreateItem mocks base method.
func (m *MockItemUseCase) CreateItem(item *domain.Item) (*domain.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", item)
	ret0, _ := ret[0].(*domain.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MockItemUseCaseMockRecorder) CreateItem(item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockItemUseCase)(nil).CreateItem), item)
}

// CreateItems mocks base method.
func (m *MockItemUseCase) CreateItems(items []*domain.Item) ([]*domain.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItems", items)
	ret0, _ := ret[0].([]*domain.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateItems indicates an expected call of CreateItems.
func (mr *MockItemUseCaseMockRecorder) CreateItems(items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItems", reflect.TypeOf((*MockItemUseCase)(nil).CreateItems), items)
}

// DeleteItem mocks base method.
func (m *MockItemUseCase) DeleteItem(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockItemUseCaseMockRecorder) DeleteItem(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockItemUseCase)(nil).DeleteItem), id)
}

// GetItemByID mocks base method.
func (m *MockItemUseCase) GetItemByID(id int) (*domain.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByID", id)
	ret0, _ := ret[0].(*domain.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByID indicates an expected call of GetItemByID.
func (mr *MockItemUseCaseMockRecorder) GetItemByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByID", reflect.TypeOf((*MockItemUseCase)(nil).GetItemByID), id)
}

// GetItemDetailByID mocks base method.
func (m *MockItemUseCase) GetItemDetailByID(id int) (*domain.ItemDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemDetailByID", id)
	ret0, _ := ret[0].(*domain.ItemDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemDetailByID indicates an expected call of GetItemDetailByID.
func (mr *MockItemUseCaseMockRecorder) GetItemDetailByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemDetailByID", reflect.TypeOf((*MockItemUseCase)(nil).GetItemDetailByID), id)
}

// SearchItems mocks base method.
func (m *MockItemUseCase) SearchItems(query domain.ItemSearchQuery) ([]*domain.ItemDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchItems", query)
	ret0, _ := ret[0].([]*domain.ItemDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchItems indicates an expected call of SearchItems.
func (mr *MockItemUseCaseMockRecorder) SearchItems(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchItems", reflect.TypeOf((*MockItemUseCase)(nil).SearchItems), query)
}

// UpdateItem mocks base method.
func (m *MockItemUseCase) UpdateItem(item *domain.Item) (*domain.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", item)
	ret0, _ := ret[0].(*domain.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockItemUseCaseMockRecorder) UpdateItem(item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockItemUseCase)(nil).UpdateItem), item)
}
