// Code generated by MockGen. DO NOT EDIT.
// Source: comment.go

package mock_usecase

import (
	reflect "reflect"

	"github.com/golang/mock/gomock"
	"github.com/traPtitech/booQ-v3/domain"
)

type MockCommentUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCommentUsecaseMockRecorder
}

type MockCommentUsecaseMockRecorder struct {
	mock *MockCommentUsecase
}

func NewMockCommentUsecase(ctrl *gomock.Controller) *MockCommentUsecase {
	mock := &MockCommentUsecase{ctrl: ctrl}
	mock.recorder = &MockCommentUsecaseMockRecorder{mock}
	return mock
}

func (m *MockCommentUsecase) EXPECT() *MockCommentUsecaseMockRecorder {
	return m.recorder
}

func (m *MockCommentUsecase) CreateComment(itemID int, userID string, text string) (*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", itemID, userID, text)
	ret0, _ := ret[0].(*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCommentUsecaseMockRecorder) CreateComment(itemID, userID, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockCommentUsecase)(nil).CreateComment), itemID, userID, text)
}
