// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 画像ファイルをアップロードします。
	// (POST /files)
	PostFile(ctx echo.Context) error
	// 画像ファイルをダウンロードします。
	// (GET /files/{fileId})
	GetFile(ctx echo.Context, fileId FileIdInPath) error
	// 物品の一覧を取得します。
	// (GET /items)
	GetItems(ctx echo.Context, params GetItemsParams) error
	// 物品を新しく登録します。
	// (POST /items)
	PostItem(ctx echo.Context) error
	// 物品を削除します。
	// (DELETE /items/{itemId})
	DeleteItem(ctx echo.Context, itemId ItemIdInPath) error
	// 物品の詳細情報を取得します。
	// (GET /items/{itemId})
	GetItem(ctx echo.Context, itemId ItemIdInPath) error
	// 物品の情報を変更します。
	// (PATCH /items/{itemId})
	EditItem(ctx echo.Context, itemId ItemIdInPath) error
	// 備品を借ります。
	// (POST /items/{itemId}/borrowing/equipment)
	PostBorrowEquipment(ctx echo.Context, itemId ItemIdInPath) error
	// 備品を返します。
	// (POST /items/{itemId}/borrowing/equipment/return)
	PostBorrowEquipmentReturn(ctx echo.Context, itemId ItemIdInPath) error
	// コメントを新規作成します。
	// (POST /items/{itemId}/comments)
	PostComment(ctx echo.Context, itemId ItemIdInPath) error
	// 物品のいいねを取り消します。
	// (DELETE /items/{itemId}/likes)
	RemoveLike(ctx echo.Context, itemId ItemIdInPath) error
	// 物品にいいねをつけます。
	// (POST /items/{itemId}/likes)
	AddLike(ctx echo.Context, itemId ItemIdInPath) error
	// 物品の所有者を追加します。
	// (POST /items/{itemId}/owners)
	PostItemOwners(ctx echo.Context, itemId ItemIdInPath) error
	// 物品の所有者を削除します
	// (DELETE /items/{itemId}/owners/{ownershipId})
	DeleteItemOwners(ctx echo.Context, itemId ItemIdInPath, ownershipId OwnershipIdInPath) error
	// 物品の所有者を編集します。(所有者と管理者のみ)
	// (PATCH /items/{itemId}/owners/{ownershipId})
	EditItemOwners(ctx echo.Context, itemId ItemIdInPath, ownershipId OwnershipIdInPath) error
	// 個人所有物を「借りたい」と意見表明します。
	// (POST /items/{itemId}/owners/{ownershipId}/borrowings)
	PostBorrow(ctx echo.Context, itemId ItemIdInPath, ownershipId OwnershipIdInPath) error
	// 個人所有物を借りたいという要望を取得します。 (○○日に借りたい、○○日に返す予定、など)
	// (GET /items/{itemId}/owners/{ownershipId}/borrowings/{borrowingId})
	GetBorrowingById(ctx echo.Context, itemId ItemIdInPath, ownershipId OwnershipIdInPath, borrowingId BorrowingIdInPath) error
	// 個人所有物を○○日まで借りたいという要望に対して返答します。
	// (POST /items/{itemId}/owners/{ownershipId}/borrowings/{borrowingId}/reply)
	PostBorrowReply(ctx echo.Context, itemId ItemIdInPath, ownershipId OwnershipIdInPath, borrowingId BorrowingIdInPath) error
	// 個人所有物を返します。
	// (POST /items/{itemId}/owners/{ownershipId}/borrowings/{borrowingId}/return)
	PostReturn(ctx echo.Context, itemId ItemIdInPath, ownershipId OwnershipIdInPath, borrowingId BorrowingIdInPath) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostFile converts echo context to params.
func (w *ServerInterfaceWrapper) PostFile(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFile(ctx)
	return err
}

// GetFile converts echo context to params.
func (w *ServerInterfaceWrapper) GetFile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "fileId" -------------
	var fileId FileIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "fileId", ctx.Param("fileId"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fileId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetFile(ctx, fileId)
	return err
}

// GetItems converts echo context to params.
func (w *ServerInterfaceWrapper) GetItems(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetItemsParams
	// ------------- Optional query parameter "userId" -------------

	err = runtime.BindQueryParameter("form", true, false, "userId", ctx.QueryParams(), &params.UserId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "rental" -------------

	err = runtime.BindQueryParameter("form", true, false, "rental", ctx.QueryParams(), &params.Rental)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter rental: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", ctx.QueryParams(), &params.Tag)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag: %s", err))
	}

	// ------------- Optional query parameter "tag-exclude" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag-exclude", ctx.QueryParams(), &params.TagExclude)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag-exclude: %s", err))
	}

	// ------------- Optional query parameter "sortby" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortby", ctx.QueryParams(), &params.Sortby)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sortby: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetItems(ctx, params)
	return err
}

// PostItem converts echo context to params.
func (w *ServerInterfaceWrapper) PostItem(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostItem(ctx)
	return err
}

// DeleteItem converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteItem(ctx, itemId)
	return err
}

// GetItem converts echo context to params.
func (w *ServerInterfaceWrapper) GetItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetItem(ctx, itemId)
	return err
}

// EditItem converts echo context to params.
func (w *ServerInterfaceWrapper) EditItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.EditItem(ctx, itemId)
	return err
}

// PostBorrowEquipment converts echo context to params.
func (w *ServerInterfaceWrapper) PostBorrowEquipment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostBorrowEquipment(ctx, itemId)
	return err
}

// PostBorrowEquipmentReturn converts echo context to params.
func (w *ServerInterfaceWrapper) PostBorrowEquipmentReturn(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostBorrowEquipmentReturn(ctx, itemId)
	return err
}

// PostComment converts echo context to params.
func (w *ServerInterfaceWrapper) PostComment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostComment(ctx, itemId)
	return err
}

// RemoveLike converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveLike(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RemoveLike(ctx, itemId)
	return err
}

// AddLike converts echo context to params.
func (w *ServerInterfaceWrapper) AddLike(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddLike(ctx, itemId)
	return err
}

// PostItemOwners converts echo context to params.
func (w *ServerInterfaceWrapper) PostItemOwners(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostItemOwners(ctx, itemId)
	return err
}

// DeleteItemOwners converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteItemOwners(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// ------------- Path parameter "ownershipId" -------------
	var ownershipId OwnershipIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "ownershipId", ctx.Param("ownershipId"), &ownershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ownershipId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteItemOwners(ctx, itemId, ownershipId)
	return err
}

// EditItemOwners converts echo context to params.
func (w *ServerInterfaceWrapper) EditItemOwners(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// ------------- Path parameter "ownershipId" -------------
	var ownershipId OwnershipIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "ownershipId", ctx.Param("ownershipId"), &ownershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ownershipId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.EditItemOwners(ctx, itemId, ownershipId)
	return err
}

// PostBorrow converts echo context to params.
func (w *ServerInterfaceWrapper) PostBorrow(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// ------------- Path parameter "ownershipId" -------------
	var ownershipId OwnershipIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "ownershipId", ctx.Param("ownershipId"), &ownershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ownershipId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostBorrow(ctx, itemId, ownershipId)
	return err
}

// GetBorrowingById converts echo context to params.
func (w *ServerInterfaceWrapper) GetBorrowingById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// ------------- Path parameter "ownershipId" -------------
	var ownershipId OwnershipIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "ownershipId", ctx.Param("ownershipId"), &ownershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ownershipId: %s", err))
	}

	// ------------- Path parameter "borrowingId" -------------
	var borrowingId BorrowingIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "borrowingId", ctx.Param("borrowingId"), &borrowingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter borrowingId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBorrowingById(ctx, itemId, ownershipId, borrowingId)
	return err
}

// PostBorrowReply converts echo context to params.
func (w *ServerInterfaceWrapper) PostBorrowReply(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// ------------- Path parameter "ownershipId" -------------
	var ownershipId OwnershipIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "ownershipId", ctx.Param("ownershipId"), &ownershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ownershipId: %s", err))
	}

	// ------------- Path parameter "borrowingId" -------------
	var borrowingId BorrowingIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "borrowingId", ctx.Param("borrowingId"), &borrowingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter borrowingId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostBorrowReply(ctx, itemId, ownershipId, borrowingId)
	return err
}

// PostReturn converts echo context to params.
func (w *ServerInterfaceWrapper) PostReturn(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// ------------- Path parameter "ownershipId" -------------
	var ownershipId OwnershipIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "ownershipId", ctx.Param("ownershipId"), &ownershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ownershipId: %s", err))
	}

	// ------------- Path parameter "borrowingId" -------------
	var borrowingId BorrowingIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "borrowingId", ctx.Param("borrowingId"), &borrowingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter borrowingId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostReturn(ctx, itemId, ownershipId, borrowingId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/files", wrapper.PostFile)
	router.GET(baseURL+"/files/:fileId", wrapper.GetFile)
	router.GET(baseURL+"/items", wrapper.GetItems)
	router.POST(baseURL+"/items", wrapper.PostItem)
	router.DELETE(baseURL+"/items/:itemId", wrapper.DeleteItem)
	router.GET(baseURL+"/items/:itemId", wrapper.GetItem)
	router.PATCH(baseURL+"/items/:itemId", wrapper.EditItem)
	router.POST(baseURL+"/items/:itemId/borrowing/equipment", wrapper.PostBorrowEquipment)
	router.POST(baseURL+"/items/:itemId/borrowing/equipment/return", wrapper.PostBorrowEquipmentReturn)
	router.POST(baseURL+"/items/:itemId/comments", wrapper.PostComment)
	router.DELETE(baseURL+"/items/:itemId/likes", wrapper.RemoveLike)
	router.POST(baseURL+"/items/:itemId/likes", wrapper.AddLike)
	router.POST(baseURL+"/items/:itemId/owners", wrapper.PostItemOwners)
	router.DELETE(baseURL+"/items/:itemId/owners/:ownershipId", wrapper.DeleteItemOwners)
	router.PATCH(baseURL+"/items/:itemId/owners/:ownershipId", wrapper.EditItemOwners)
	router.POST(baseURL+"/items/:itemId/owners/:ownershipId/borrowings", wrapper.PostBorrow)
	router.GET(baseURL+"/items/:itemId/owners/:ownershipId/borrowings/:borrowingId", wrapper.GetBorrowingById)
	router.POST(baseURL+"/items/:itemId/owners/:ownershipId/borrowings/:borrowingId/reply", wrapper.PostBorrowReply)
	router.POST(baseURL+"/items/:itemId/owners/:ownershipId/borrowings/:borrowingId/return", wrapper.PostReturn)

}
