// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc61MTWZv/V6ze/TBTFUhA6x2Hqvng5d0pdmdW1n3ny05RW01ygNYkHbs7jhRFVZ8O",
	"ckswiFyM4CsKQgCJvMqrDBf5Xzzp7uTT/Atb53Qnfc89iu58sTDp81zO8zvP7TydUSrIRmJsFEQFnuoZ",
	"pWI0R0eAADjyvwGW49jfmOhQb6g32kcLw/jDEOCDHBMTGDZK9VDKtKisTivZ7d7rlI9i8Ecx/KCPitIR",
	"QPWYaVA+igN34gwHQlSPwMWBj+KDwyBCY7LCSAw/zkQFMAQ4amzMRw0yYeDNGSUWkfQcSRsosevFXKNQ",
	"L19GAJEKfKUXhOkESqx58dUo1MuX/S0KOH6YiTWx3SYa9bIX6Ap2xl96sCTr6mM2VvrWBLObIBYeIRjk",
	"2BjgBAaQL+ko/xvg8F/gHh2JhQlHLg4oX4nsAMuGAR2lxnwYzBEQFaxPd/u7AwjuFhNZObeB4K56mkNw",
	"FsEPCGYMKrzAMdEhshGGIr+W2Buk+8sr2IFbIChgtiUF7sQBLzhV0L7ujV4LxwdusmykRmVCcXCdFoBN",
	"mUD3pY5Ad0fXXygfNchyEVqgeqgQfs6hio/IwfI2EoWdPQTPEHyGYBLBdf0PaRqJUtXtKMnkcypVdWP+",
	"eifOxErmackOBdm4zdhdPgfYvqqNFOJc1Ll9ArhnwzyCEpJmEEwhmEVwAsEFBJcQHCeoX8aSilLx6Qs1",
	"c2qSfauWA0F4eYuIl5yjA8CEqsOj5bZlsDes08Amz2XduyAHaAGErtidWqDr+47Adx3dl//W3d0TCPQE",
	"Av9j35AOgYkA4pjp0I0odq6aY3bsUgiEQZM8ovFwmB7AyzQeVXk6LeOxxGQpHFZJTAiHbwxSPb+OUv/K",
	"gUGqh/oXv5HG+PXI4sdP/3c8EqG5EWqs306/HOfrF8N53OT9dGHnlTo9heBreSOtfniAYE4+S6hzE0o6",
	"LU9k8EmUphBMK+k0AVIKwU1yHjeRCJXHa+rCMV4uzRfWV+VcCsEMkpJIkhDMIbiL4A4BIVkiJZEo4QOO",
	"j3aKhLJsYWu9sPMKwTUEH+KDLEkYwJKY//BcFjcQfE0cQhLBrCI+LfmBjCuYfVQ8Fmo75OI84Gx7T/Hf",
	"V1/pdtTK2ZZOVAeKbiif6QiZdTPD3u1E4tzReRw12FbJRCv7mzgXrkzjl5s/mYlQfjrG+LE4vL+rNueD",
	"WbjpxPBXWfZ25ZxWzebkqZcXlNVXJCLsIDjuV1ZfYcaMQOTRqbi5bIa3RPmqXGQxmT860rJavyxl5EfQ",
	"wsig5sqtbn/Qx/ICCFFjvlGKjQJ9kc3hlpIKp+XIVz/T9zwSaLMZNCqmJf2Yp5VTOVfXkCWACPmjkg7l",
	"JcQPaSLQHEePOAQwEe/H3s+uJAk3tTMuxacxzxOqi0HqiNrpCvRQdZr2FAQz8Bk6OJHer4PjOhBoJlwf",
	"RCqCQ+DoKE8HMaCtSK9NWWO1sbiaId1ZusDJ/GAjItUliRuowsxtwF8d+YXX2wdlAWwu3hEM6rI+4VLB",
	"5voRdyZSbMiW433/3eVLgUtdge6/XApcdJPLpb4IBNxc+teapFn8t5lrcfexsva8S/79ACc6G2kkQvlw",
	"orj7+I+TKQSPSSKS/ONkGsHXxZUX8tt3WvYs597Jk0e4AhGh8vQf+aNXOLmRxkvJzaxemYjryvLLYmYW",
	"STPquyc4p5GSxZUsgrn84R4SYXHlYeEwjeAbTEqCCKaLidP8yRMEc+r0ZPHJfRy6SiIh+Dp/OKuITwt7",
	"+wjuFBKn8swKkuaVFERwQ95/KL98ixLHxcxpIb1K5H+D4A4RfleePCJkJ3DKJaYQ3ENwEokwfzyjaaRk",
	"DnAyh3O1KSTOkszsKUnvXqsvp0jKVcrJRKhuH2G+2hJCXHn6EklJLA9+DJcZH8XFj+IiEiV5Y1sWMwjm",
	"Cjtn8nwKwZSalIwsEKaVjJQ/XscbKMIiTMoPTxHcVc+O5ZNxBBc1qbB22EZZXU2YKkzu4DIG5tSFZwjO",
	"Kku/I2keiakiPFRm/o5VIKmnOr1d2Pk7tsXie/V9FofuRBIlnqPECZLeo8QWSrzV0lYkPpA3tpX9ZYyE",
	"vTkkpnHOKkJlaV/55/vCzpq6sq4+XS9M7hSOdhFMyc/eq3sTWhUqP3iWP13VsmePZLShOiEy9EspyRqk",
	"42F8DiwZ1bAgxPgevz/I3gVcJxsD0YFQ562Y3+IROm/FhlwlKidRFUOJ9hR5/m8cHevVc5XKayxhQeuv",
	"OeuMC+b9dpPQEYGdT9hidvtTfrc0lSho2SCfkVyafU/ZpI0m8+ZasP5swFYC8D8xt4EVlhX9qSljxcHr",
	"Go4qfL2odomCOiFfWSL3oEgyQbd4WFPzrAWhrR2hrKFOD9mJ3hoe5EBUoPVQ6bCy06otOD21F8g1nKuS",
	"nqaK2KSRzyhOGjpLRg3iUR3X39RppAsTARHW3vScIR2TZSTNkhCZIxXsKoJvSDfkEflvmoTaRQTH3VPR",
	"uixvTp/ry7Sbsa+z4WExL9kZN8vFWF645tVo/Lq7WrV2sfEW3fAGuBN07UJWg/ioExG4/HYo6ZV3VGVO",
	"FrqysR4TWyAaBsHbbFz431CTzf6vtgqLg6b3hmnIw/I8PWRn6+/6znSbuoXgTOHNIUnnl73uVC1X2/XL",
	"EYtzTV7QYC5CnIv+7KYRgk8IgawLSf1kZ4ib29M9lOli7Y8T6M2taaPxAi3EeWcjNfADSuwg6TWSskj6",
	"HSWmlMMpLLkIu37QjKFV2Vqx3P1D4WxBnj0oP3TR8pCSnJfnNm1d6+pG+dIuCayDEWU3qW+xAXY7VEzH",
	"z2dzVVY7N5pOuTYF/99cA34u39Zo1tk6X/Snd/jTO1TzDmQaLTrIavV6VKCDgpGgYc/Rp1/2GS2tIUYY",
	"jg90BtkIrjj6BEYAwWH/AMv+V8fdi46eLqV/gaR/osQJSszhf2HuSl+vHvc0BOv3cSUqPuou4HiNwMXO",
	"QGeAhPgYiNIxpvyRj4yJEXxql5fEqbHagBR2bTQWARuQ6mN54d+YMNCHyAAvXGVDIyWldX8YiYcFJkZz",
	"gh/DpSNEC2S2zJgyszrM0vWtVd2LP18lScoWgrl/7/vRd6HvP380X72awTjARGluxCXpHbNCSJ8m4AAf",
	"Y6O8xr070GUTn47FwkyQ6Oy/xWt5sCF7pcKRaEJ4WnW58R942y8FAk4184ezyt46rq+snsAwKhnBKzXE",
	"KHXhWE6kzRuBpHnS802gxDJK7BFwTJdTPB0WpM34K6VZtx+T1K+pR7XByzEs2RBwsfiPwDC4ZdsCtm1j",
	"IvQQ8N+KgSHrhtVgJa/9ulT59h3BlLz3WF7NlrRdwVlgjVuWEJG0iRJva90yn2Xi1qMfaTzit4zEku6e",
	"v9zk9droXvKAg5NtsDQ1Keee6LNhiU3S5n+nOQPtdr58LSA/gvlDsbC5haR5Ob0kf1i26UhGRO/EAbGK",
	"7qoMj2ofCjW8sl0keW5W3dpHMIVrjakJzHTyoDkxeEBzweH6xKiwM7L4jBQDegOjUam0Ur3OzTGIP0Nw",
	"PH/8TlncJ5daZWl1pg4XgJfoz8OUfD9bTJCLNZ3CFJJm5I0nCI7LawfyHOn9lJ/RVNM6N1jxynqFmQgj",
	"UJWnjqvohRKTZMPPEMwVl5LyVlJeO1CmxTZpqm4fYUb3Z+WpZQRThbMF081kZWXZwUEe1Kutq8RYW2mf",
	"tMg29GZaU/AS6CGLWLXeCrVW3GJmQ95YMjcJPGTtAPeC4XgItEjm/OkigrnCJlQP1kgP8ZQ45im9FwmT",
	"Xq6C5YSBkYqHsr9q9Koc9Gsa0LBMMTrUrScpcFgvVUoTyOCvLbwR6xln3gNvpXimqdKvN1DdMzz9gs87",
	"w2vRbpVnvFw2q7VZW0tEshrpmlYl1GzExCp2kdK6zZokX8EkLrq8Q5LdLmbmSAtLKnlxnOO4I0CaV5b2",
	"idXTaua4mHpTBQHllMQ/qtXYY5oEuMhx4uI6+byMDOdhqj2FMw0XuqZwXurJ0zPFzEZVXFfKrqgmHUE1",
	"+OhjbHXmtI1tCMwVtt+qB/tK4r689o86zn1deazlFSsySUYLwWHnBv81xDTrN2o9m7W4h9aatUn/Xe3o",
	"txITBho2ppWVg7p9gL/8dogfWJqcTaLGM9hcJfzM48PtwI/H+02fuEFQSYr2RpcWQEwb+sbI0ospJ6w0",
	"/WoHlp8z3pP6RPjS38xqL8oIi8+ELYP3l4MoUr4t140o82x82/BTGsNoD2LMgx6fGDBBM9tzjxUkvSVD",
	"rW8xP5LqFjbT+dNVZWrOAzrGWwdu2NGG0y0Jr01AmCFa7OpvcpNbF3XmnXI/iWBOb0SIEG9CYhslTr65",
	"FAh864plK6Zuggh7F/zE3AY1JdLK3rp8eIjgrjX7xfV8g01lT5OU+jRkIhk+azgFIb2FcQT3tJwUSTPK",
	"uykPI+nvCLQgLdUPsIcRDZmwHKXGR/PWvBIKuZuyq4IprcKcb2vumq1JGkcPK9nR5aRpN3Yt9NG27Tle",
	"Koj3y91vJbuN3cOj2fzpqtY5KvcMy+W0fHa/sAnN92buPRBtvKyNnt+YX/vEvp+1Mq7g/etoS7SnniFW",
	"xRbGh/FUnlnz8CQ6zCpA0D9qujweq+T724Apo39iQlWtXZTzZARbF8bNAs05c1/V550/v2JpTLTdlqVe",
	"x3nzD4FP4x/OIyrV99niyoTZNXxjfA2zau65Ojeh4QDBs2+b8BtGHdt0TGsY6VWK3U/RQ/nUiHRhfp77",
	"cebX5dXpbe3NvVLjhNyXirMIZpXxdGEzWXieVR4/aKQCrgJQ/6jpR70qznhcLT13dUQfSm+rHasMfpxX",
	"G1oMCLPk34nCJlRWV1z77xe++bic/LicVJZf4grOYn5o/oqUGZn80RRO2UVI3rfY/tYVBZ8huFZf5Pz9",
	"OdPIS4Nw9XPl3xn7MhSu7pi1X05rr3fGHD6Tby6z/rJOtekgfkBwq9Ihh7vya61e3yycLah7C2132i1q",
	"kZ+TY3DOuu8VSq7zCtaaWuWYBuDuug8Qxjg2FA/qb2tbR5IHWPZOx92LnQJHxzpvxfx0jKGcgzq8QA/h",
	"AO66OgTuligITCcZaXanEmaDZJTOoNHj95MPh1le6LkcuBzQVvaXVbSTKPeoiksvtFruSl+v9bc9eRfO",
	"llay1+Jy99i53qXR6UVFa4tVIGEqUjxI6PWJJ41yViIlUWJRH2f1IlbCiAs1bUrWZZLYg5Q2GDvWP/Z/",
	"AQAA//+jxkVKmlYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
