// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// BorrowReply defines model for borrowReply.
type BorrowReply struct {
	// Answer Example: true
	Answer bool `json:"answer"`

	// Comment Example: 2/20に部室に置きます
	Comment string `json:"comment"`
}

// BorrowRequest defines model for borrowRequest.
type BorrowRequest struct {
	// BorrowInClubRoom Example: true
	BorrowInClubRoom bool `json:"borrowInClubRoom"`

	// DueDate Example: 2024-02-16
	DueDate openapi_types.Date `json:"dueDate"`

	// Propose Example: 読みたかったから。
	Propose *string `json:"propose,omitempty"`
}

// BorrowRequestEquipment defines model for borrowRequestEquipment.
type BorrowRequestEquipment struct {
	// BorrowInClubRoom Example: true
	BorrowInClubRoom bool `json:"borrowInClubRoom"`

	// Count Example: 1
	Count *int `json:"count,omitempty"`

	// DueDate Example: 2024-02-16
	DueDate openapi_types.Date `json:"dueDate"`

	// Propose Example: 読みたかったから。
	Propose *string `json:"propose,omitempty"`
}

// BorrowReturn defines model for borrowReturn.
type BorrowReturn struct {
	// Text Example: ありがとうございました。面白かったです
	Text string `json:"text"`
}

// Borrowing defines model for borrowing.
type Borrowing struct {
	// BorrowInClubRoom Example: true
	BorrowInClubRoom bool `json:"borrowInClubRoom"`

	// DueDate Example: 2024-02-16
	DueDate openapi_types.Date `json:"dueDate"`

	// Id Example: 1
	Id int `json:"id"`

	// Propose Example: 読みたかったから。
	Propose *string `json:"propose,omitempty"`
}

// Comment defines model for comment.
type Comment struct {
	// CreatedAt Example: 2019-07-28T22:00:00Z
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DeletedAt Example: 2019-07-28T22:00:00Z
	DeletedAt nullable.Nullable[time.Time] `json:"deletedAt,omitempty"`

	// Id Example: 1
	Id   *int         `json:"id,omitempty"`
	Item *ItemSummary `json:"item,omitempty"`

	// ItemId Example: 1
	ItemId *int `json:"itemId,omitempty"`

	// Text Example: 小説版は夏美の心理描写がよく描かれていて、映画版を補完するものになっている。あとがきと解説だけでも読む価値はあると思います。
	Text string `json:"text"`

	// UpdatedAt Example: 2019-07-28T22:00:00Z
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// UserId Example: s9
	UserId *string `json:"userId,omitempty"`
}

// File defines model for file.
type File struct {
	// Id ファイルID
	//
	// Example: 1
	Id int `json:"id"`

	// Url ファイルURL
	//
	// Example: /api/files/1
	Url string `json:"url"`
}

// IsBook アイテム種別 本でない/本
type IsBook = bool

// IsEquipment アイテム種別 個人所有/備品
type IsEquipment = bool

// Item defines model for item.
type Item struct {
	// Code Example: 9784041026403
	Code     *string    `json:"code,omitempty"`
	Comments *[]Comment `json:"comments,omitempty"`

	// Count Example: 100
	Count *int `json:"count,omitempty"`

	// CreatedAt Example: 2019-07-28T22:00:00Z
	CreatedAt time.Time `json:"createdAt"`

	// DeletedAt Example: 2019-07-28T22:00:00Z
	DeletedAt nullable.Nullable[time.Time] `json:"deletedAt"`

	// Description Example: 高校1年の夏、帆高（ほだか）は離島から家出し、東京にやってきた。連日降り続ける雨の中、雑踏ひしめく都会の片隅で、帆高は不思議な能力を持つ少女・陽菜（ひな）に出会う。「ねぇ、今から晴れるよ」。それは祈るだけで、空を晴れに出来る力だった――。天候の調和が狂っていく時代に、運命に翻弄される少年と少女が自らの生き方を「選択」する物語。長編アニメーション映画『天気の子』の、新海誠監督自身が執筆した原作小説。
	Description string `json:"description"`

	// Id Example: 1
	Id int `json:"id"`

	// ImgUrl Example: https://cover.openbd.jp/9784041026403.jpg
	ImgUrl string `json:"imgUrl"`

	// IsBook アイテム種別 本でない/本
	IsBook IsBook `json:"isBook"`

	// IsTrapItem アイテム種別 個人所有/備品
	IsTrapItem IsEquipment `json:"isTrapItem"`

	// Name Example: 小説 天気の子
	Name string `json:"name"`
	Tags *[]Tag `json:"tags,omitempty"`

	// UpdatedAt Example: 2019-07-28T22:00:00Z
	UpdatedAt time.Time `json:"updatedAt"`
	union     json.RawMessage
}

// Item0 defines model for Item.0.
type Item0 struct {
	Count    int `json:"count"`
	CountMax int `json:"countMax"`
}

// Item1 defines model for Item.1.
type Item1 struct {
	Ownerships []Ownership `json:"ownerships"`
}

// ItemDetail defines model for itemDetail.
type ItemDetail struct {
	// Code Example: 9784041026403
	Code     *string    `json:"code,omitempty"`
	Comments *[]Comment `json:"comments,omitempty"`

	// Count Example: 100
	Count *int `json:"count,omitempty"`

	// CreatedAt Example: 2019-07-28T22:00:00Z
	CreatedAt time.Time `json:"createdAt"`

	// DeletedAt Example: 2019-07-28T22:00:00Z
	DeletedAt nullable.Nullable[time.Time] `json:"deletedAt"`

	// Description Example: 高校1年の夏、帆高（ほだか）は離島から家出し、東京にやってきた。連日降り続ける雨の中、雑踏ひしめく都会の片隅で、帆高は不思議な能力を持つ少女・陽菜（ひな）に出会う。「ねぇ、今から晴れるよ」。それは祈るだけで、空を晴れに出来る力だった――。天候の調和が狂っていく時代に、運命に翻弄される少年と少女が自らの生き方を「選択」する物語。長編アニメーション映画『天気の子』の、新海誠監督自身が執筆した原作小説。
	Description string `json:"description"`

	// Id Example: 1
	Id int `json:"id"`

	// ImgUrl Example: https://cover.openbd.jp/9784041026403.jpg
	ImgUrl string `json:"imgUrl"`

	// IsBook アイテム種別 本でない/本
	IsBook IsBook `json:"isBook"`

	// IsTrapItem アイテム種別 個人所有/備品
	IsTrapItem   IsEquipment `json:"isTrapItem"`
	LikesByUsers *[]string   `json:"likesByUsers,omitempty"`

	// Name Example: 小説 天気の子
	Name string `json:"name"`
	Tags *[]Tag `json:"tags,omitempty"`

	// UpdatedAt Example: 2019-07-28T22:00:00Z
	UpdatedAt time.Time `json:"updatedAt"`
	union     json.RawMessage
}

// ItemDetail0 defines model for ItemDetail.0.
type ItemDetail0 struct {
	TransactionsEquipment []TransactionEquipment `json:"transactionsEquipment"`
}

// ItemDetail1 defines model for ItemDetail.1.
type ItemDetail1 struct {
	Transactions []Transaction `json:"transactions"`
}

// ItemDetail2 defines model for ItemDetail.2.
type ItemDetail2 struct {
	Count    int `json:"count"`
	CountMax int `json:"countMax"`
}

// ItemDetail3 defines model for ItemDetail.3.
type ItemDetail3 struct {
	Ownerships []Ownership `json:"ownerships"`
}

// ItemPostRequest defines model for itemPostRequest.
type ItemPostRequest struct {
	// Code Example: 9784041026403
	Code *string `json:"code,omitempty"`

	// Count Example: 100
	Count *int `json:"count,omitempty"`

	// Description Example: 高校1年の夏、帆高（ほだか）は離島から家出し、東京にやってきた。連日降り続ける雨の中、雑踏ひしめく都会の片隅で、帆高は不思議な能力を持つ少女・陽菜（ひな）に出会う。「ねぇ、今から晴れるよ」。それは祈るだけで、空を晴れに出来る力だった――。天候の調和が狂っていく時代に、運命に翻弄される少年と少女が自らの生き方を「選択」する物語。長編アニメーション映画『天気の子』の、新海誠監督自身が執筆した原作小説。
	Description string `json:"description"`

	// ImgUrl Example: https://cover.openbd.jp/9784041026403.jpg
	ImgUrl string `json:"imgUrl"`

	// IsBook アイテム種別 本でない/本
	IsBook IsBook `json:"isBook"`

	// IsTrapItem アイテム種別 個人所有/備品
	IsTrapItem IsEquipment `json:"isTrapItem"`

	// Name Example: 小説 天気の子
	Name string    `json:"name"`
	Tags *[]string `json:"tags,omitempty"`
}

// ItemPosted defines model for itemPosted.
type ItemPosted struct {
	// Code Example: 9784041026403
	Code *string `json:"code,omitempty"`

	// Count Example: 100
	Count *int `json:"count,omitempty"`

	// CreatedAt Example: 2019-07-28T22:00:00Z
	CreatedAt time.Time `json:"createdAt"`

	// DeletedAt Example: 2019-07-28T22:00:00Z
	DeletedAt nullable.Nullable[time.Time] `json:"deletedAt"`

	// Description Example: 高校1年の夏、帆高（ほだか）は離島から家出し、東京にやってきた。連日降り続ける雨の中、雑踏ひしめく都会の片隅で、帆高は不思議な能力を持つ少女・陽菜（ひな）に出会う。「ねぇ、今から晴れるよ」。それは祈るだけで、空を晴れに出来る力だった――。天候の調和が狂っていく時代に、運命に翻弄される少年と少女が自らの生き方を「選択」する物語。長編アニメーション映画『天気の子』の、新海誠監督自身が執筆した原作小説。
	Description string `json:"description"`

	// Id Example: 1
	Id int `json:"id"`

	// ImgUrl Example: https://cover.openbd.jp/9784041026403.jpg
	ImgUrl string `json:"imgUrl"`

	// IsBook アイテム種別 本でない/本
	IsBook IsBook `json:"isBook"`

	// IsTrapItem アイテム種別 個人所有/備品
	IsTrapItem IsEquipment `json:"isTrapItem"`

	// Name Example: 小説 天気の子
	Name string    `json:"name"`
	Tags *[]string `json:"tags,omitempty"`

	// UpdatedAt Example: 2019-07-28T22:00:00Z
	UpdatedAt time.Time `json:"updatedAt"`
}

// ItemSummary defines model for itemSummary.
type ItemSummary struct {
	// Code Example: 9784041026403
	Code     *string    `json:"code,omitempty"`
	Comments *[]Comment `json:"comments,omitempty"`

	// Count Example: 100
	Count *int `json:"count,omitempty"`

	// CreatedAt Example: 2019-07-28T22:00:00Z
	CreatedAt time.Time `json:"createdAt"`

	// DeletedAt Example: 2019-07-28T22:00:00Z
	DeletedAt nullable.Nullable[time.Time] `json:"deletedAt"`

	// Description Example: 高校1年の夏、帆高（ほだか）は離島から家出し、東京にやってきた。連日降り続ける雨の中、雑踏ひしめく都会の片隅で、帆高は不思議な能力を持つ少女・陽菜（ひな）に出会う。「ねぇ、今から晴れるよ」。それは祈るだけで、空を晴れに出来る力だった――。天候の調和が狂っていく時代に、運命に翻弄される少年と少女が自らの生き方を「選択」する物語。長編アニメーション映画『天気の子』の、新海誠監督自身が執筆した原作小説。
	Description string `json:"description"`

	// Id Example: 1
	Id int `json:"id"`

	// ImgUrl Example: https://cover.openbd.jp/9784041026403.jpg
	ImgUrl string `json:"imgUrl"`

	// IsBook アイテム種別 本でない/本
	IsBook IsBook `json:"isBook"`

	// IsLiked Example: true
	IsLiked *bool `json:"isLiked,omitempty"`

	// IsTrapItem アイテム種別 個人所有/備品
	IsTrapItem IsEquipment `json:"isTrapItem"`

	// LikeCounts Example: 1
	LikeCounts *int `json:"likeCounts,omitempty"`

	// Name Example: 小説 天気の子
	Name string `json:"name"`
	Tags *[]Tag `json:"tags,omitempty"`

	// UpdatedAt Example: 2019-07-28T22:00:00Z
	UpdatedAt time.Time `json:"updatedAt"`
	union     json.RawMessage
}

// ItemSummary0 defines model for ItemSummary.0.
type ItemSummary0 struct {
	Count    int `json:"count"`
	CountMax int `json:"countMax"`
}

// ItemSummary1 defines model for ItemSummary.1.
type ItemSummary1 struct {
	Ownerships []Ownership `json:"ownerships"`
}

// Owner defines model for owner.
type Owner struct {
	// Count Example: 1
	Count int `json:"count"`

	// CreatedAt Example: 2019-07-28T22:00:00Z
	CreatedAt time.Time `json:"createdAt"`

	// DeletedAt Example: 2019-07-28T22:00:00Z
	DeletedAt time.Time `json:"deletedAt"`

	// Id Example: 1
	Id int `json:"id"`

	// OwnerId Example: 1
	OwnerId int `json:"ownerId"`

	// Rentalable Example: true
	Rentalable bool `json:"rentalable"`

	// UpdatedAt Example: 2019-07-28T22:00:00Z
	UpdatedAt time.Time `json:"updatedAt"`

	// UserId Example: s9
	UserId string `json:"userId"`
}

// Ownership defines model for ownership.
type Ownership struct {
	// Id Example: 1
	Id *int `json:"id,omitempty"`

	// ItemId Example: 1
	ItemId *int `json:"itemId,omitempty"`

	// Memo Example: おもしろいのでぜひ読んでください
	Memo string `json:"memo"`

	// Rentalable Example: true
	Rentalable  bool         `json:"rentalable"`
	Transaction *Transaction `json:"transaction,omitempty"`

	// UserId Example: s9
	UserId string `json:"userId"`
}

// PostComment defines model for postComment.
type PostComment struct {
	// Text Example: 小説版は夏美の心理描写がよく描かれていて、映画版を補完するものになっている。あとがきと解説だけでも読む価値はあると思います。
	Text string `json:"text"`
}

// PostOwnership defines model for postOwnership.
type PostOwnership struct {
	// Memo Example: 読んでください
	Memo string `json:"memo"`

	// Rentalable Example: true
	Rentalable bool `json:"rentalable"`

	// UserId Example: s9
	UserId string `json:"userId"`
}

// Tag defines model for tag.
type Tag struct {
	// Name Example: 小説
	Name string `json:"name"`
}

// Transaction defines model for transaction.
type Transaction struct {
	// CheckoutDate Example: 2024-02-16
	CheckoutDate openapi_types.Date `json:"checkout_date"`

	// CreatedAt Example: 2019-07-28T22:00:00Z
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DeletedAt Example: 2019-07-28T22:00:00Z
	DeletedAt nullable.Nullable[time.Time] `json:"deletedAt,omitempty"`

	// DueDate Example: 2024-02-16
	DueDate openapi_types.Date `json:"due_date"`

	// Id Example: 1
	Id *int `json:"id,omitempty"`

	// Message Example: 2/17に部室でお貸しします
	Message string `json:"message"`

	// OwnershipId Example: 1
	OwnershipId *int `json:"ownershipId,omitempty"`

	// Purpose Example: 読みたかったから。
	Purpose *string `json:"purpose,omitempty"`

	// ReturnMessage Example: ずっと読みたかったんですよね。ありがとう！
	ReturnMessage string `json:"returnMessage"`

	// ReturnDate Example: 2024-02-16
	ReturnDate openapi_types.Date `json:"return_date"`

	// Status 0=リクエスト済み、1=貸し出し中、2=返却済み、3=貸し出し拒否
	//
	// Example: 1
	Status *int `json:"status,omitempty"`

	// UpdatedAt Example: 2019-07-28T22:00:00Z
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// UserId Example: s9
	UserId *string `json:"userId,omitempty"`
}

// TransactionEquipment defines model for transactionEquipment.
type TransactionEquipment struct {
	// CreatedAt Example: 2019-07-28T22:00:00Z
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DeletedAt Example: 2019-07-28T22:00:00Z
	DeletedAt nullable.Nullable[time.Time] `json:"deletedAt,omitempty"`

	// DueDate Example: 2024-02-16
	DueDate openapi_types.Date `json:"due_date"`

	// Id Example: 1
	Id *int `json:"id,omitempty"`

	// ItemId Example: 1
	ItemId *int `json:"itemId,omitempty"`

	// Purpose Example: 読みたかったから。
	Purpose *string `json:"purpose,omitempty"`

	// ReturnDate Example: 2024-02-16
	ReturnDate openapi_types.Date `json:"return_date"`

	// Status 0=リクエスト済み、1=貸し出し中、2=返却済み、3=貸し出し拒否
	//
	// Example: 1
	Status *int `json:"status,omitempty"`

	// UpdatedAt Example: 2019-07-28T22:00:00Z
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// UserId Example: s9
	UserId *string `json:"userId,omitempty"`
}

// BorrowingIdInPath defines model for borrowingIdInPath.
type BorrowingIdInPath = int

// FileIdInPath defines model for fileIdInPath.
type FileIdInPath = int

// ItemIdInPath defines model for itemIdInPath.
type ItemIdInPath = int

// OwnershipIdInPath defines model for ownershipIdInPath.
type OwnershipIdInPath = int

// TagIdInPath defines model for tagIdInPath.
type TagIdInPath = int

// PostFileMultipartBody defines parameters for PostFile.
type PostFileMultipartBody struct {
	// File 3MBまでのJPG, PNGファイル
	File *openapi_types.File `json:"file,omitempty"`
}

// GetItemsParams defines parameters for GetItems.
type GetItemsParams struct {
	// UserId 指定したユーザーの所有する物品一覧を取得します。
	UserId *string `form:"userId,omitempty" json:"userId,omitempty"`

	// Search 名称が部分一致する物品一覧を取得します。
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// Rental 指定したユーザーの借りている物品一覧を取得します。
	Rental *string `form:"rental,omitempty" json:"rental,omitempty"`

	// Limit 取得したい件数を指定します。リクエストした件数が全部の件数より多い場合は全部の一覧になります。
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset 取得したいデータの開始場所を指定します。リクエストした件数が全部の件数より多い場合は空の配列が返ってきます。
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Tag リクエストしたタグのついている物品一覧を取得します。
	Tag *[]string `form:"tag,omitempty" json:"tag,omitempty"`

	// TagExclude リクエストしたタグのついている物品一覧を除外します
	TagExclude *[]string `form:"tag-exclude,omitempty" json:"tag-exclude,omitempty"`

	// Sortby 何の要素でソートするか
	Sortby *string `form:"sortby,omitempty" json:"sortby,omitempty"`
}

// PostItemJSONBody defines parameters for PostItem.
type PostItemJSONBody = []ItemPostRequest

// PostFileMultipartRequestBody defines body for PostFile for multipart/form-data ContentType.
type PostFileMultipartRequestBody PostFileMultipartBody

// PostItemJSONRequestBody defines body for PostItem for application/json ContentType.
type PostItemJSONRequestBody = PostItemJSONBody

// EditItemJSONRequestBody defines body for EditItem for application/json ContentType.
type EditItemJSONRequestBody = ItemPostRequest

// PostBorrowEquipmentJSONRequestBody defines body for PostBorrowEquipment for application/json ContentType.
type PostBorrowEquipmentJSONRequestBody = BorrowRequestEquipment

// PostBorrowEquipmentReturnJSONRequestBody defines body for PostBorrowEquipmentReturn for application/json ContentType.
type PostBorrowEquipmentReturnJSONRequestBody = BorrowReturn

// PostCommentJSONRequestBody defines body for PostComment for application/json ContentType.
type PostCommentJSONRequestBody = PostComment

// PostItemOwnersJSONRequestBody defines body for PostItemOwners for application/json ContentType.
type PostItemOwnersJSONRequestBody = PostOwnership

// EditItemOwnersJSONRequestBody defines body for EditItemOwners for application/json ContentType.
type EditItemOwnersJSONRequestBody = PostOwnership

// PostBorrowJSONRequestBody defines body for PostBorrow for application/json ContentType.
type PostBorrowJSONRequestBody = BorrowRequest

// PostBorrowReplyJSONRequestBody defines body for PostBorrowReply for application/json ContentType.
type PostBorrowReplyJSONRequestBody = BorrowReply

// PostReturnJSONRequestBody defines body for PostReturn for application/json ContentType.
type PostReturnJSONRequestBody = BorrowReturn

// AsItem0 returns the union data inside the Item as a Item0
func (t Item) AsItem0() (Item0, error) {
	var body Item0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromItem0 overwrites any union data inside the Item as the provided Item0
func (t *Item) FromItem0(v Item0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeItem0 performs a merge with any union data inside the Item, using the provided Item0
func (t *Item) MergeItem0(v Item0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsItem1 returns the union data inside the Item as a Item1
func (t Item) AsItem1() (Item1, error) {
	var body Item1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromItem1 overwrites any union data inside the Item as the provided Item1
func (t *Item) FromItem1(v Item1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeItem1 performs a merge with any union data inside the Item, using the provided Item1
func (t *Item) MergeItem1(v Item1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if t.Comments != nil {
		object["comments"], err = json.Marshal(t.Comments)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'comments': %w", err)
		}
	}

	if t.Count != nil {
		object["count"], err = json.Marshal(t.Count)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'count': %w", err)
		}
	}

	object["createdAt"], err = json.Marshal(t.CreatedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'createdAt': %w", err)
	}

	object["deletedAt"], err = json.Marshal(t.DeletedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'deletedAt': %w", err)
	}

	object["description"], err = json.Marshal(t.Description)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'description': %w", err)
	}

	object["id"], err = json.Marshal(t.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["imgUrl"], err = json.Marshal(t.ImgUrl)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'imgUrl': %w", err)
	}

	object["isBook"], err = json.Marshal(t.IsBook)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'isBook': %w", err)
	}

	object["isTrapItem"], err = json.Marshal(t.IsTrapItem)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'isTrapItem': %w", err)
	}

	object["name"], err = json.Marshal(t.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if t.Tags != nil {
		object["tags"], err = json.Marshal(t.Tags)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tags': %w", err)
		}
	}

	object["updatedAt"], err = json.Marshal(t.UpdatedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'updatedAt': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["comments"]; found {
		err = json.Unmarshal(raw, &t.Comments)
		if err != nil {
			return fmt.Errorf("error reading 'comments': %w", err)
		}
	}

	if raw, found := object["count"]; found {
		err = json.Unmarshal(raw, &t.Count)
		if err != nil {
			return fmt.Errorf("error reading 'count': %w", err)
		}
	}

	if raw, found := object["createdAt"]; found {
		err = json.Unmarshal(raw, &t.CreatedAt)
		if err != nil {
			return fmt.Errorf("error reading 'createdAt': %w", err)
		}
	}

	if raw, found := object["deletedAt"]; found {
		err = json.Unmarshal(raw, &t.DeletedAt)
		if err != nil {
			return fmt.Errorf("error reading 'deletedAt': %w", err)
		}
	}

	if raw, found := object["description"]; found {
		err = json.Unmarshal(raw, &t.Description)
		if err != nil {
			return fmt.Errorf("error reading 'description': %w", err)
		}
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &t.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
	}

	if raw, found := object["imgUrl"]; found {
		err = json.Unmarshal(raw, &t.ImgUrl)
		if err != nil {
			return fmt.Errorf("error reading 'imgUrl': %w", err)
		}
	}

	if raw, found := object["isBook"]; found {
		err = json.Unmarshal(raw, &t.IsBook)
		if err != nil {
			return fmt.Errorf("error reading 'isBook': %w", err)
		}
	}

	if raw, found := object["isTrapItem"]; found {
		err = json.Unmarshal(raw, &t.IsTrapItem)
		if err != nil {
			return fmt.Errorf("error reading 'isTrapItem': %w", err)
		}
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &t.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
	}

	if raw, found := object["tags"]; found {
		err = json.Unmarshal(raw, &t.Tags)
		if err != nil {
			return fmt.Errorf("error reading 'tags': %w", err)
		}
	}

	if raw, found := object["updatedAt"]; found {
		err = json.Unmarshal(raw, &t.UpdatedAt)
		if err != nil {
			return fmt.Errorf("error reading 'updatedAt': %w", err)
		}
	}

	return err
}

// AsItemDetail0 returns the union data inside the ItemDetail as a ItemDetail0
func (t ItemDetail) AsItemDetail0() (ItemDetail0, error) {
	var body ItemDetail0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromItemDetail0 overwrites any union data inside the ItemDetail as the provided ItemDetail0
func (t *ItemDetail) FromItemDetail0(v ItemDetail0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeItemDetail0 performs a merge with any union data inside the ItemDetail, using the provided ItemDetail0
func (t *ItemDetail) MergeItemDetail0(v ItemDetail0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsItemDetail1 returns the union data inside the ItemDetail as a ItemDetail1
func (t ItemDetail) AsItemDetail1() (ItemDetail1, error) {
	var body ItemDetail1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromItemDetail1 overwrites any union data inside the ItemDetail as the provided ItemDetail1
func (t *ItemDetail) FromItemDetail1(v ItemDetail1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeItemDetail1 performs a merge with any union data inside the ItemDetail, using the provided ItemDetail1
func (t *ItemDetail) MergeItemDetail1(v ItemDetail1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsItemDetail2 returns the union data inside the ItemDetail as a ItemDetail2
func (t ItemDetail) AsItemDetail2() (ItemDetail2, error) {
	var body ItemDetail2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromItemDetail2 overwrites any union data inside the ItemDetail as the provided ItemDetail2
func (t *ItemDetail) FromItemDetail2(v ItemDetail2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeItemDetail2 performs a merge with any union data inside the ItemDetail, using the provided ItemDetail2
func (t *ItemDetail) MergeItemDetail2(v ItemDetail2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsItemDetail3 returns the union data inside the ItemDetail as a ItemDetail3
func (t ItemDetail) AsItemDetail3() (ItemDetail3, error) {
	var body ItemDetail3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromItemDetail3 overwrites any union data inside the ItemDetail as the provided ItemDetail3
func (t *ItemDetail) FromItemDetail3(v ItemDetail3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeItemDetail3 performs a merge with any union data inside the ItemDetail, using the provided ItemDetail3
func (t *ItemDetail) MergeItemDetail3(v ItemDetail3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ItemDetail) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if t.Comments != nil {
		object["comments"], err = json.Marshal(t.Comments)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'comments': %w", err)
		}
	}

	if t.Count != nil {
		object["count"], err = json.Marshal(t.Count)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'count': %w", err)
		}
	}

	object["createdAt"], err = json.Marshal(t.CreatedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'createdAt': %w", err)
	}

	object["deletedAt"], err = json.Marshal(t.DeletedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'deletedAt': %w", err)
	}

	object["description"], err = json.Marshal(t.Description)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'description': %w", err)
	}

	object["id"], err = json.Marshal(t.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["imgUrl"], err = json.Marshal(t.ImgUrl)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'imgUrl': %w", err)
	}

	object["isBook"], err = json.Marshal(t.IsBook)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'isBook': %w", err)
	}

	object["isTrapItem"], err = json.Marshal(t.IsTrapItem)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'isTrapItem': %w", err)
	}

	if t.LikesByUsers != nil {
		object["likesByUsers"], err = json.Marshal(t.LikesByUsers)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'likesByUsers': %w", err)
		}
	}

	object["name"], err = json.Marshal(t.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if t.Tags != nil {
		object["tags"], err = json.Marshal(t.Tags)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tags': %w", err)
		}
	}

	object["updatedAt"], err = json.Marshal(t.UpdatedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'updatedAt': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *ItemDetail) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["comments"]; found {
		err = json.Unmarshal(raw, &t.Comments)
		if err != nil {
			return fmt.Errorf("error reading 'comments': %w", err)
		}
	}

	if raw, found := object["count"]; found {
		err = json.Unmarshal(raw, &t.Count)
		if err != nil {
			return fmt.Errorf("error reading 'count': %w", err)
		}
	}

	if raw, found := object["createdAt"]; found {
		err = json.Unmarshal(raw, &t.CreatedAt)
		if err != nil {
			return fmt.Errorf("error reading 'createdAt': %w", err)
		}
	}

	if raw, found := object["deletedAt"]; found {
		err = json.Unmarshal(raw, &t.DeletedAt)
		if err != nil {
			return fmt.Errorf("error reading 'deletedAt': %w", err)
		}
	}

	if raw, found := object["description"]; found {
		err = json.Unmarshal(raw, &t.Description)
		if err != nil {
			return fmt.Errorf("error reading 'description': %w", err)
		}
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &t.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
	}

	if raw, found := object["imgUrl"]; found {
		err = json.Unmarshal(raw, &t.ImgUrl)
		if err != nil {
			return fmt.Errorf("error reading 'imgUrl': %w", err)
		}
	}

	if raw, found := object["isBook"]; found {
		err = json.Unmarshal(raw, &t.IsBook)
		if err != nil {
			return fmt.Errorf("error reading 'isBook': %w", err)
		}
	}

	if raw, found := object["isTrapItem"]; found {
		err = json.Unmarshal(raw, &t.IsTrapItem)
		if err != nil {
			return fmt.Errorf("error reading 'isTrapItem': %w", err)
		}
	}

	if raw, found := object["likesByUsers"]; found {
		err = json.Unmarshal(raw, &t.LikesByUsers)
		if err != nil {
			return fmt.Errorf("error reading 'likesByUsers': %w", err)
		}
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &t.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
	}

	if raw, found := object["tags"]; found {
		err = json.Unmarshal(raw, &t.Tags)
		if err != nil {
			return fmt.Errorf("error reading 'tags': %w", err)
		}
	}

	if raw, found := object["updatedAt"]; found {
		err = json.Unmarshal(raw, &t.UpdatedAt)
		if err != nil {
			return fmt.Errorf("error reading 'updatedAt': %w", err)
		}
	}

	return err
}

// AsItemSummary0 returns the union data inside the ItemSummary as a ItemSummary0
func (t ItemSummary) AsItemSummary0() (ItemSummary0, error) {
	var body ItemSummary0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromItemSummary0 overwrites any union data inside the ItemSummary as the provided ItemSummary0
func (t *ItemSummary) FromItemSummary0(v ItemSummary0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeItemSummary0 performs a merge with any union data inside the ItemSummary, using the provided ItemSummary0
func (t *ItemSummary) MergeItemSummary0(v ItemSummary0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsItemSummary1 returns the union data inside the ItemSummary as a ItemSummary1
func (t ItemSummary) AsItemSummary1() (ItemSummary1, error) {
	var body ItemSummary1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromItemSummary1 overwrites any union data inside the ItemSummary as the provided ItemSummary1
func (t *ItemSummary) FromItemSummary1(v ItemSummary1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeItemSummary1 performs a merge with any union data inside the ItemSummary, using the provided ItemSummary1
func (t *ItemSummary) MergeItemSummary1(v ItemSummary1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ItemSummary) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if t.Comments != nil {
		object["comments"], err = json.Marshal(t.Comments)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'comments': %w", err)
		}
	}

	if t.Count != nil {
		object["count"], err = json.Marshal(t.Count)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'count': %w", err)
		}
	}

	object["createdAt"], err = json.Marshal(t.CreatedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'createdAt': %w", err)
	}

	object["deletedAt"], err = json.Marshal(t.DeletedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'deletedAt': %w", err)
	}

	object["description"], err = json.Marshal(t.Description)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'description': %w", err)
	}

	object["id"], err = json.Marshal(t.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["imgUrl"], err = json.Marshal(t.ImgUrl)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'imgUrl': %w", err)
	}

	object["isBook"], err = json.Marshal(t.IsBook)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'isBook': %w", err)
	}

	object["isLiked"], err = json.Marshal(t.IsLiked)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'isLiked': %w", err)
	}

	object["isTrapItem"], err = json.Marshal(t.IsTrapItem)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'isTrapItem': %w", err)
	}

	object["likeCounts"], err = json.Marshal(t.LikeCounts)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'likeCounts': %w", err)
	}

	object["name"], err = json.Marshal(t.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if t.Tags != nil {
		object["tags"], err = json.Marshal(t.Tags)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tags': %w", err)
		}
	}

	object["updatedAt"], err = json.Marshal(t.UpdatedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'updatedAt': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *ItemSummary) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["comments"]; found {
		err = json.Unmarshal(raw, &t.Comments)
		if err != nil {
			return fmt.Errorf("error reading 'comments': %w", err)
		}
	}

	if raw, found := object["count"]; found {
		err = json.Unmarshal(raw, &t.Count)
		if err != nil {
			return fmt.Errorf("error reading 'count': %w", err)
		}
	}

	if raw, found := object["createdAt"]; found {
		err = json.Unmarshal(raw, &t.CreatedAt)
		if err != nil {
			return fmt.Errorf("error reading 'createdAt': %w", err)
		}
	}

	if raw, found := object["deletedAt"]; found {
		err = json.Unmarshal(raw, &t.DeletedAt)
		if err != nil {
			return fmt.Errorf("error reading 'deletedAt': %w", err)
		}
	}

	if raw, found := object["description"]; found {
		err = json.Unmarshal(raw, &t.Description)
		if err != nil {
			return fmt.Errorf("error reading 'description': %w", err)
		}
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &t.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
	}

	if raw, found := object["imgUrl"]; found {
		err = json.Unmarshal(raw, &t.ImgUrl)
		if err != nil {
			return fmt.Errorf("error reading 'imgUrl': %w", err)
		}
	}

	if raw, found := object["isBook"]; found {
		err = json.Unmarshal(raw, &t.IsBook)
		if err != nil {
			return fmt.Errorf("error reading 'isBook': %w", err)
		}
	}

	if raw, found := object["isLiked"]; found {
		err = json.Unmarshal(raw, &t.IsLiked)
		if err != nil {
			return fmt.Errorf("error reading 'isLiked': %w", err)
		}
	}

	if raw, found := object["isTrapItem"]; found {
		err = json.Unmarshal(raw, &t.IsTrapItem)
		if err != nil {
			return fmt.Errorf("error reading 'isTrapItem': %w", err)
		}
	}

	if raw, found := object["likeCounts"]; found {
		err = json.Unmarshal(raw, &t.LikeCounts)
		if err != nil {
			return fmt.Errorf("error reading 'likeCounts': %w", err)
		}
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &t.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
	}

	if raw, found := object["tags"]; found {
		err = json.Unmarshal(raw, &t.Tags)
		if err != nil {
			return fmt.Errorf("error reading 'tags': %w", err)
		}
	}

	if raw, found := object["updatedAt"]; found {
		err = json.Unmarshal(raw, &t.UpdatedAt)
		if err != nil {
			return fmt.Errorf("error reading 'updatedAt': %w", err)
		}
	}

	return err
}
