// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// BorrowReply defines model for borrowReply.
type BorrowReply struct {
	Answer  bool   `json:"answer"`
	Comment string `json:"comment"`
}

// BorrowRequest defines model for borrowRequest.
type BorrowRequest struct {
	BorrowInClubRoom bool               `json:"borrowInClubRoom"`
	DueDate          openapi_types.Date `json:"dueDate"`
	Propose          *string            `json:"propose,omitempty"`
}

// BorrowRequestEquipment defines model for borrowRequestEquipment.
type BorrowRequestEquipment struct {
	BorrowInClubRoom bool               `json:"borrowInClubRoom"`
	Count            *int               `json:"count,omitempty"`
	DueDate          openapi_types.Date `json:"dueDate"`
	Propose          *string            `json:"propose,omitempty"`
}

// BorrowReturn defines model for borrowReturn.
type BorrowReturn struct {
	Text string `json:"text"`
}

// Borrowing defines model for borrowing.
type Borrowing struct {
	BorrowInClubRoom bool               `json:"borrowInClubRoom"`
	DueDate          openapi_types.Date `json:"dueDate"`
	Id               int                `json:"id"`
	Propose          *string            `json:"propose,omitempty"`
}

// Comment defines model for comment.
type Comment struct {
	CreatedAt *time.Time                   `json:"createdAt,omitempty"`
	DeletedAt nullable.Nullable[time.Time] `json:"deletedAt,omitempty"`
	Id        *int                         `json:"id,omitempty"`
	Item      *ItemSummary                 `json:"item,omitempty"`
	ItemId    *int                         `json:"itemId,omitempty"`
	Text      string                       `json:"text"`
	UpdatedAt *time.Time                   `json:"updatedAt,omitempty"`
	UserId    *string                      `json:"userId,omitempty"`
}

// File defines model for file.
type File struct {
	// Id ファイルID
	Id int `json:"id"`

	// Url ファイルURL
	Url string `json:"url"`
}

// IsBook アイテム種別 本でない/本
type IsBook = bool

// IsEquipment アイテム種別 個人所有/備品
type IsEquipment = bool

// Item defines model for item.
type Item struct {
	Code        *string                      `json:"code,omitempty"`
	Comments    *[]Comment                   `json:"comments,omitempty"`
	Count       *int                         `json:"count,omitempty"`
	CreatedAt   time.Time                    `json:"createdAt"`
	DeletedAt   nullable.Nullable[time.Time] `json:"deletedAt"`
	Description string                       `json:"description"`
	Id          int                          `json:"id"`
	ImgUrl      string                       `json:"imgUrl"`

	// IsBook アイテム種別 本でない/本
	IsBook IsBook `json:"isBook"`

	// IsTrapItem アイテム種別 個人所有/備品
	IsTrapItem IsEquipment `json:"isTrapItem"`
	Name       string      `json:"name"`
	Tags       *[]Tag      `json:"tags,omitempty"`
	UpdatedAt  time.Time   `json:"updatedAt"`
	union      json.RawMessage
}

// Item0 defines model for .
type Item0 struct {
	Count    int `json:"count"`
	CountMax int `json:"countMax"`
}

// Item1 defines model for .
type Item1 struct {
	Ownerships []Ownership `json:"ownerships"`
}

// ItemDetail defines model for itemDetail.
type ItemDetail struct {
	Code        *string                      `json:"code,omitempty"`
	Comments    *[]Comment                   `json:"comments,omitempty"`
	Count       *int                         `json:"count,omitempty"`
	CreatedAt   time.Time                    `json:"createdAt"`
	DeletedAt   nullable.Nullable[time.Time] `json:"deletedAt"`
	Description string                       `json:"description"`
	Id          int                          `json:"id"`
	ImgUrl      string                       `json:"imgUrl"`

	// IsBook アイテム種別 本でない/本
	IsBook IsBook `json:"isBook"`

	// IsTrapItem アイテム種別 個人所有/備品
	IsTrapItem   IsEquipment `json:"isTrapItem"`
	LikesByUsers *[]string   `json:"likesByUsers,omitempty"`
	Name         string      `json:"name"`
	Tags         *[]Tag      `json:"tags,omitempty"`
	UpdatedAt    time.Time   `json:"updatedAt"`
	union        json.RawMessage
}

// ItemDetail0 defines model for .
type ItemDetail0 struct {
	TransactionsEquipment []TransactionEquipment `json:"transactionsEquipment"`
}

// ItemDetail1 defines model for .
type ItemDetail1 struct {
	Transactions []Transaction `json:"transactions"`
}

// ItemPostRequest defines model for itemPostRequest.
type ItemPostRequest struct {
	Code        *string `json:"code,omitempty"`
	Count       *int    `json:"count,omitempty"`
	Description string  `json:"description"`
	ImgUrl      string  `json:"imgUrl"`

	// IsBook アイテム種別 本でない/本
	IsBook IsBook `json:"isBook"`

	// IsTrapItem アイテム種別 個人所有/備品
	IsTrapItem IsEquipment `json:"isTrapItem"`
	Name       string      `json:"name"`
	Tags       *[]string   `json:"tags,omitempty"`
}

// ItemPosted defines model for itemPosted.
type ItemPosted struct {
	Code        *string                      `json:"code,omitempty"`
	Count       *int                         `json:"count,omitempty"`
	CreatedAt   time.Time                    `json:"createdAt"`
	DeletedAt   nullable.Nullable[time.Time] `json:"deletedAt"`
	Description string                       `json:"description"`
	Id          int                          `json:"id"`
	ImgUrl      string                       `json:"imgUrl"`

	// IsBook アイテム種別 本でない/本
	IsBook IsBook `json:"isBook"`

	// IsTrapItem アイテム種別 個人所有/備品
	IsTrapItem IsEquipment `json:"isTrapItem"`
	Name       string      `json:"name"`
	Tags       *[]string   `json:"tags,omitempty"`
	UpdatedAt  time.Time   `json:"updatedAt"`
}

// ItemSummary defines model for itemSummary.
type ItemSummary struct {
	Code        *string                      `json:"code,omitempty"`
	Comments    *[]Comment                   `json:"comments,omitempty"`
	Count       *int                         `json:"count,omitempty"`
	CreatedAt   time.Time                    `json:"createdAt"`
	DeletedAt   nullable.Nullable[time.Time] `json:"deletedAt"`
	Description string                       `json:"description"`
	Id          int                          `json:"id"`
	ImgUrl      string                       `json:"imgUrl"`

	// IsBook アイテム種別 本でない/本
	IsBook  IsBook `json:"isBook"`
	IsLiked *bool  `json:"isLiked,omitempty"`

	// IsTrapItem アイテム種別 個人所有/備品
	IsTrapItem IsEquipment `json:"isTrapItem"`
	LikeCounts *int        `json:"likeCounts,omitempty"`
	Name       string      `json:"name"`
	Tags       *[]Tag      `json:"tags,omitempty"`
	UpdatedAt  time.Time   `json:"updatedAt"`
}

// Owner defines model for owner.
type Owner struct {
	Count      int       `json:"count"`
	CreatedAt  time.Time `json:"createdAt"`
	DeletedAt  time.Time `json:"deletedAt"`
	Id         int       `json:"id"`
	OwnerId    int       `json:"ownerId"`
	Rentalable bool      `json:"rentalable"`
	UpdatedAt  time.Time `json:"updatedAt"`
	UserId     string    `json:"userId"`
}

// Ownership defines model for ownership.
type Ownership struct {
	Id          *int         `json:"id,omitempty"`
	ItemId      *int         `json:"itemId,omitempty"`
	Memo        string       `json:"memo"`
	Rentalable  bool         `json:"rentalable"`
	Transaction *Transaction `json:"transaction,omitempty"`
	UserId      string       `json:"userId"`
}

// PostComment defines model for postComment.
type PostComment struct {
	Text string `json:"text"`
}

// PostOwnership defines model for postOwnership.
type PostOwnership struct {
	Memo       string `json:"memo"`
	Rentalable bool   `json:"rentalable"`
	UserId     string `json:"userId"`
}

// Tag defines model for tag.
type Tag struct {
	Name string `json:"name"`
}

// Transaction defines model for transaction.
type Transaction struct {
	CheckoutDate  openapi_types.Date           `json:"checkout_date"`
	CreatedAt     *time.Time                   `json:"createdAt,omitempty"`
	DeletedAt     nullable.Nullable[time.Time] `json:"deletedAt,omitempty"`
	DueDate       openapi_types.Date           `json:"due_date"`
	Id            *int                         `json:"id,omitempty"`
	Message       string                       `json:"message"`
	OwnershipId   *int                         `json:"ownershipId,omitempty"`
	Purpose       *string                      `json:"purpose,omitempty"`
	ReturnMessage string                       `json:"returnMessage"`
	ReturnDate    openapi_types.Date           `json:"return_date"`

	// Status 0=リクエスト済み、1=貸し出し中、2=返却済み、3=貸し出し拒否
	Status    *int       `json:"status,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	UserId    *string    `json:"userId,omitempty"`
}

// TransactionEquipment defines model for transactionEquipment.
type TransactionEquipment struct {
	CreatedAt  *time.Time                   `json:"createdAt,omitempty"`
	DeletedAt  nullable.Nullable[time.Time] `json:"deletedAt,omitempty"`
	DueDate    openapi_types.Date           `json:"due_date"`
	Id         *int                         `json:"id,omitempty"`
	ItemId     *int                         `json:"itemId,omitempty"`
	Purpose    *string                      `json:"purpose,omitempty"`
	ReturnDate openapi_types.Date           `json:"return_date"`

	// Status 0=リクエスト済み、1=貸し出し中、2=返却済み、3=貸し出し拒否
	Status    *int       `json:"status,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	UserId    *string    `json:"userId,omitempty"`
}

// BorrowingIdInPath defines model for borrowingIdInPath.
type BorrowingIdInPath = int

// FileIdInPath defines model for fileIdInPath.
type FileIdInPath = int

// ItemIdInPath defines model for itemIdInPath.
type ItemIdInPath = int

// OwnershipIdInPath defines model for ownershipIdInPath.
type OwnershipIdInPath = int

// TagIdInPath defines model for tagIdInPath.
type TagIdInPath = int

// PostFileMultipartBody defines parameters for PostFile.
type PostFileMultipartBody struct {
	// File 3MBまでのJPG, PNGファイル
	File *openapi_types.File `json:"file,omitempty"`
}

// GetItemsParams defines parameters for GetItems.
type GetItemsParams struct {
	// UserId 指定したユーザーの所有する物品一覧を取得します。
	UserId *string `form:"userId,omitempty" json:"userId,omitempty"`

	// Search 名称が部分一致する物品一覧を取得します。
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// Rental 指定したユーザーの借りている物品一覧を取得します。
	Rental *string `form:"rental,omitempty" json:"rental,omitempty"`

	// Limit 取得したい件数を指定します。リクエストした件数が全部の件数より多い場合は全部の一覧になります。
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset 取得したいデータの開始場所を指定します。リクエストした件数が全部の件数より多い場合は空の配列が返ってきます。
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Tag リクエストしたタグのついている物品一覧を取得します。
	Tag *[]string `form:"tag,omitempty" json:"tag,omitempty"`

	// TagExclude リクエストしたタグのついている物品一覧を除外します
	TagExclude *[]string `form:"tag-exclude,omitempty" json:"tag-exclude,omitempty"`

	// Sortby 何の要素でソートするか
	Sortby *string `form:"sortby,omitempty" json:"sortby,omitempty"`
}

// PostItemJSONBody defines parameters for PostItem.
type PostItemJSONBody = []ItemPostRequest

// PostFileMultipartRequestBody defines body for PostFile for multipart/form-data ContentType.
type PostFileMultipartRequestBody PostFileMultipartBody

// PostItemJSONRequestBody defines body for PostItem for application/json ContentType.
type PostItemJSONRequestBody = PostItemJSONBody

// EditItemJSONRequestBody defines body for EditItem for application/json ContentType.
type EditItemJSONRequestBody = ItemPostRequest

// PostBorrowEquipmentJSONRequestBody defines body for PostBorrowEquipment for application/json ContentType.
type PostBorrowEquipmentJSONRequestBody = BorrowRequestEquipment

// PostBorrowEquipmentReturnJSONRequestBody defines body for PostBorrowEquipmentReturn for application/json ContentType.
type PostBorrowEquipmentReturnJSONRequestBody = BorrowReturn

// PostCommentJSONRequestBody defines body for PostComment for application/json ContentType.
type PostCommentJSONRequestBody = PostComment

// PostItemOwnersJSONRequestBody defines body for PostItemOwners for application/json ContentType.
type PostItemOwnersJSONRequestBody = PostOwnership

// EditItemOwnersJSONRequestBody defines body for EditItemOwners for application/json ContentType.
type EditItemOwnersJSONRequestBody = PostOwnership

// PostBorrowJSONRequestBody defines body for PostBorrow for application/json ContentType.
type PostBorrowJSONRequestBody = BorrowRequest

// PostBorrowReplyJSONRequestBody defines body for PostBorrowReply for application/json ContentType.
type PostBorrowReplyJSONRequestBody = BorrowReply

// PostReturnJSONRequestBody defines body for PostReturn for application/json ContentType.
type PostReturnJSONRequestBody = BorrowReturn

// AsItem0 returns the union data inside the Item as a Item0
func (t Item) AsItem0() (Item0, error) {
	var body Item0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromItem0 overwrites any union data inside the Item as the provided Item0
func (t *Item) FromItem0(v Item0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeItem0 performs a merge with any union data inside the Item, using the provided Item0
func (t *Item) MergeItem0(v Item0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsItem1 returns the union data inside the Item as a Item1
func (t Item) AsItem1() (Item1, error) {
	var body Item1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromItem1 overwrites any union data inside the Item as the provided Item1
func (t *Item) FromItem1(v Item1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeItem1 performs a merge with any union data inside the Item, using the provided Item1
func (t *Item) MergeItem1(v Item1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	object["comments"], err = json.Marshal(t.Comments)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'comments': %w", err)
	}

	if t.Count != nil {
		object["count"], err = json.Marshal(t.Count)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'count': %w", err)
		}
	}

	object["createdAt"], err = json.Marshal(t.CreatedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'createdAt': %w", err)
	}

	object["deletedAt"], err = json.Marshal(t.DeletedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'deletedAt': %w", err)
	}

	object["description"], err = json.Marshal(t.Description)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'description': %w", err)
	}

	object["id"], err = json.Marshal(t.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["imgUrl"], err = json.Marshal(t.ImgUrl)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'imgUrl': %w", err)
	}

	object["isBook"], err = json.Marshal(t.IsBook)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'isBook': %w", err)
	}

	object["isTrapItem"], err = json.Marshal(t.IsTrapItem)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'isTrapItem': %w", err)
	}

	object["name"], err = json.Marshal(t.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	object["tags"], err = json.Marshal(t.Tags)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'tags': %w", err)
	}

	object["updatedAt"], err = json.Marshal(t.UpdatedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'updatedAt': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["comments"]; found {
		err = json.Unmarshal(raw, &t.Comments)
		if err != nil {
			return fmt.Errorf("error reading 'comments': %w", err)
		}
	}

	if raw, found := object["count"]; found {
		err = json.Unmarshal(raw, &t.Count)
		if err != nil {
			return fmt.Errorf("error reading 'count': %w", err)
		}
	}

	if raw, found := object["createdAt"]; found {
		err = json.Unmarshal(raw, &t.CreatedAt)
		if err != nil {
			return fmt.Errorf("error reading 'createdAt': %w", err)
		}
	}

	if raw, found := object["deletedAt"]; found {
		err = json.Unmarshal(raw, &t.DeletedAt)
		if err != nil {
			return fmt.Errorf("error reading 'deletedAt': %w", err)
		}
	}

	if raw, found := object["description"]; found {
		err = json.Unmarshal(raw, &t.Description)
		if err != nil {
			return fmt.Errorf("error reading 'description': %w", err)
		}
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &t.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
	}

	if raw, found := object["imgUrl"]; found {
		err = json.Unmarshal(raw, &t.ImgUrl)
		if err != nil {
			return fmt.Errorf("error reading 'imgUrl': %w", err)
		}
	}

	if raw, found := object["isBook"]; found {
		err = json.Unmarshal(raw, &t.IsBook)
		if err != nil {
			return fmt.Errorf("error reading 'isBook': %w", err)
		}
	}

	if raw, found := object["isTrapItem"]; found {
		err = json.Unmarshal(raw, &t.IsTrapItem)
		if err != nil {
			return fmt.Errorf("error reading 'isTrapItem': %w", err)
		}
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &t.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
	}

	if raw, found := object["tags"]; found {
		err = json.Unmarshal(raw, &t.Tags)
		if err != nil {
			return fmt.Errorf("error reading 'tags': %w", err)
		}
	}

	if raw, found := object["updatedAt"]; found {
		err = json.Unmarshal(raw, &t.UpdatedAt)
		if err != nil {
			return fmt.Errorf("error reading 'updatedAt': %w", err)
		}
	}

	return err
}

// AsItemDetail0 returns the union data inside the ItemDetail as a ItemDetail0
func (t ItemDetail) AsItemDetail0() (ItemDetail0, error) {
	var body ItemDetail0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromItemDetail0 overwrites any union data inside the ItemDetail as the provided ItemDetail0
func (t *ItemDetail) FromItemDetail0(v ItemDetail0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeItemDetail0 performs a merge with any union data inside the ItemDetail, using the provided ItemDetail0
func (t *ItemDetail) MergeItemDetail0(v ItemDetail0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsItemDetail1 returns the union data inside the ItemDetail as a ItemDetail1
func (t ItemDetail) AsItemDetail1() (ItemDetail1, error) {
	var body ItemDetail1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromItemDetail1 overwrites any union data inside the ItemDetail as the provided ItemDetail1
func (t *ItemDetail) FromItemDetail1(v ItemDetail1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeItemDetail1 performs a merge with any union data inside the ItemDetail, using the provided ItemDetail1
func (t *ItemDetail) MergeItemDetail1(v ItemDetail1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ItemDetail) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	object["comments"], err = json.Marshal(t.Comments)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'comments': %w", err)
	}

	if t.Count != nil {
		object["count"], err = json.Marshal(t.Count)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'count': %w", err)
		}
	}

	object["createdAt"], err = json.Marshal(t.CreatedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'createdAt': %w", err)
	}

	object["deletedAt"], err = json.Marshal(t.DeletedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'deletedAt': %w", err)
	}

	object["description"], err = json.Marshal(t.Description)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'description': %w", err)
	}

	object["id"], err = json.Marshal(t.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["imgUrl"], err = json.Marshal(t.ImgUrl)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'imgUrl': %w", err)
	}

	object["isBook"], err = json.Marshal(t.IsBook)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'isBook': %w", err)
	}

	object["isTrapItem"], err = json.Marshal(t.IsTrapItem)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'isTrapItem': %w", err)
	}

	if t.LikesByUsers != nil {
		object["likesByUsers"], err = json.Marshal(t.LikesByUsers)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'likesByUsers': %w", err)
		}
	}

	object["name"], err = json.Marshal(t.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	object["tags"], err = json.Marshal(t.Tags)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'tags': %w", err)
	}

	object["updatedAt"], err = json.Marshal(t.UpdatedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'updatedAt': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *ItemDetail) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["comments"]; found {
		err = json.Unmarshal(raw, &t.Comments)
		if err != nil {
			return fmt.Errorf("error reading 'comments': %w", err)
		}
	}

	if raw, found := object["count"]; found {
		err = json.Unmarshal(raw, &t.Count)
		if err != nil {
			return fmt.Errorf("error reading 'count': %w", err)
		}
	}

	if raw, found := object["createdAt"]; found {
		err = json.Unmarshal(raw, &t.CreatedAt)
		if err != nil {
			return fmt.Errorf("error reading 'createdAt': %w", err)
		}
	}

	if raw, found := object["deletedAt"]; found {
		err = json.Unmarshal(raw, &t.DeletedAt)
		if err != nil {
			return fmt.Errorf("error reading 'deletedAt': %w", err)
		}
	}

	if raw, found := object["description"]; found {
		err = json.Unmarshal(raw, &t.Description)
		if err != nil {
			return fmt.Errorf("error reading 'description': %w", err)
		}
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &t.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
	}

	if raw, found := object["imgUrl"]; found {
		err = json.Unmarshal(raw, &t.ImgUrl)
		if err != nil {
			return fmt.Errorf("error reading 'imgUrl': %w", err)
		}
	}

	if raw, found := object["isBook"]; found {
		err = json.Unmarshal(raw, &t.IsBook)
		if err != nil {
			return fmt.Errorf("error reading 'isBook': %w", err)
		}
	}

	if raw, found := object["isTrapItem"]; found {
		err = json.Unmarshal(raw, &t.IsTrapItem)
		if err != nil {
			return fmt.Errorf("error reading 'isTrapItem': %w", err)
		}
	}

	if raw, found := object["likesByUsers"]; found {
		err = json.Unmarshal(raw, &t.LikesByUsers)
		if err != nil {
			return fmt.Errorf("error reading 'likesByUsers': %w", err)
		}
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &t.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
	}

	if raw, found := object["tags"]; found {
		err = json.Unmarshal(raw, &t.Tags)
		if err != nil {
			return fmt.Errorf("error reading 'tags': %w", err)
		}
	}

	if raw, found := object["updatedAt"]; found {
		err = json.Unmarshal(raw, &t.UpdatedAt)
		if err != nil {
			return fmt.Errorf("error reading 'updatedAt': %w", err)
		}
	}

	return err
}
