// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PostFile 画像ファイルをアップロードします。
	// (POST /files)
	PostFile(ctx echo.Context) error
	// GetFile 画像ファイルをダウンロードします。
	// (GET /files/{fileId})
	GetFile(ctx echo.Context, fileId FileIdInPath) error
	// GetItems 物品の一覧を取得します。
	// (GET /items)
	GetItems(ctx echo.Context, params GetItemsParams) error
	// PostItem 物品を新しく登録します。
	// (POST /items)
	PostItem(ctx echo.Context) error
	// DeleteItem 物品を削除します。
	// (DELETE /items/{itemId})
	DeleteItem(ctx echo.Context, itemId ItemIdInPath) error
	// GetItem 物品の詳細情報を取得します。
	// (GET /items/{itemId})
	GetItem(ctx echo.Context, itemId ItemIdInPath) error
	// EditItem 物品の情報を変更します。
	// (PATCH /items/{itemId})
	EditItem(ctx echo.Context, itemId ItemIdInPath) error
	// PostBorrowEquipment 備品を借ります。
	// (POST /items/{itemId}/borrowing/equipment)
	PostBorrowEquipment(ctx echo.Context, itemId ItemIdInPath) error
	// PostBorrowEquipmentReturn 備品を返します。
	// (POST /items/{itemId}/borrowing/equipment/{borrowingId}/return)
	PostBorrowEquipmentReturn(ctx echo.Context, itemId ItemIdInPath, borrowingId BorrowingIdInPath) error
	// PostComment コメントを新規作成します。
	// (POST /items/{itemId}/comments)
	PostComment(ctx echo.Context, itemId ItemIdInPath) error
	// RemoveLike 物品のいいねを取り消します。
	// (DELETE /items/{itemId}/likes)
	RemoveLike(ctx echo.Context, itemId ItemIdInPath) error
	// AddLike 物品にいいねをつけます。
	// (POST /items/{itemId}/likes)
	AddLike(ctx echo.Context, itemId ItemIdInPath) error
	// PostItemOwners 物品の所有者を追加します。
	// (POST /items/{itemId}/owners)
	PostItemOwners(ctx echo.Context, itemId ItemIdInPath) error
	// DeleteItemOwners 物品の所有者を削除します
	// (DELETE /items/{itemId}/owners/{ownershipId})
	DeleteItemOwners(ctx echo.Context, itemId ItemIdInPath, ownershipId OwnershipIdInPath) error
	// EditItemOwners 物品の所有者を編集します。(所有者と管理者のみ)
	// (PATCH /items/{itemId}/owners/{ownershipId})
	EditItemOwners(ctx echo.Context, itemId ItemIdInPath, ownershipId OwnershipIdInPath) error
	// PostBorrow 個人所有物を「借りたい」と意見表明します。
	// (POST /items/{itemId}/owners/{ownershipId}/borrowings)
	PostBorrow(ctx echo.Context, itemId ItemIdInPath, ownershipId OwnershipIdInPath) error
	// GetBorrowingById 個人所有物を借りたいという要望を取得します。 (○○日に借りたい、○○日に返す予定、など)
	// (GET /items/{itemId}/owners/{ownershipId}/borrowings/{borrowingId})
	GetBorrowingById(ctx echo.Context, itemId ItemIdInPath, ownershipId OwnershipIdInPath, borrowingId BorrowingIdInPath) error
	// PostBorrowReply 個人所有物を○○日まで借りたいという要望に対して返答します。
	// (POST /items/{itemId}/owners/{ownershipId}/borrowings/{borrowingId}/reply)
	PostBorrowReply(ctx echo.Context, itemId ItemIdInPath, ownershipId OwnershipIdInPath, borrowingId BorrowingIdInPath) error
	// PostReturn 個人所有物を返します。
	// (POST /items/{itemId}/owners/{ownershipId}/borrowings/{borrowingId}/return)
	PostReturn(ctx echo.Context, itemId ItemIdInPath, ownershipId OwnershipIdInPath, borrowingId BorrowingIdInPath) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostFile converts echo context to params.
func (w *ServerInterfaceWrapper) PostFile(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFile(ctx)
	return err
}

// GetFile converts echo context to params.
func (w *ServerInterfaceWrapper) GetFile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "fileId" -------------
	var fileId FileIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "fileId", ctx.Param("fileId"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fileId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetFile(ctx, fileId)
	return err
}

// GetItems converts echo context to params.
func (w *ServerInterfaceWrapper) GetItems(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetItemsParams
	// ------------- Optional query parameter "userId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "userId", ctx.QueryParams(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", ctx.QueryParams(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "rental" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "rental", ctx.QueryParams(), &params.Rental, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter rental: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", ctx.QueryParams(), &params.Tag, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag: %s", err))
	}

	// ------------- Optional query parameter "tag-exclude" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag-exclude", ctx.QueryParams(), &params.TagExclude, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag-exclude: %s", err))
	}

	// ------------- Optional query parameter "sortby" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sortby", ctx.QueryParams(), &params.Sortby, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sortby: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetItems(ctx, params)
	return err
}

// PostItem converts echo context to params.
func (w *ServerInterfaceWrapper) PostItem(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostItem(ctx)
	return err
}

// DeleteItem converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteItem(ctx, itemId)
	return err
}

// GetItem converts echo context to params.
func (w *ServerInterfaceWrapper) GetItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetItem(ctx, itemId)
	return err
}

// EditItem converts echo context to params.
func (w *ServerInterfaceWrapper) EditItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.EditItem(ctx, itemId)
	return err
}

// PostBorrowEquipment converts echo context to params.
func (w *ServerInterfaceWrapper) PostBorrowEquipment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostBorrowEquipment(ctx, itemId)
	return err
}

// PostBorrowEquipmentReturn converts echo context to params.
func (w *ServerInterfaceWrapper) PostBorrowEquipmentReturn(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// ------------- Path parameter "borrowingId" -------------
	var borrowingId BorrowingIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "borrowingId", ctx.Param("borrowingId"), &borrowingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter borrowingId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostBorrowEquipmentReturn(ctx, itemId, borrowingId)
	return err
}

// PostComment converts echo context to params.
func (w *ServerInterfaceWrapper) PostComment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostComment(ctx, itemId)
	return err
}

// RemoveLike converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveLike(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RemoveLike(ctx, itemId)
	return err
}

// AddLike converts echo context to params.
func (w *ServerInterfaceWrapper) AddLike(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddLike(ctx, itemId)
	return err
}

// PostItemOwners converts echo context to params.
func (w *ServerInterfaceWrapper) PostItemOwners(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostItemOwners(ctx, itemId)
	return err
}

// DeleteItemOwners converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteItemOwners(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// ------------- Path parameter "ownershipId" -------------
	var ownershipId OwnershipIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "ownershipId", ctx.Param("ownershipId"), &ownershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ownershipId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteItemOwners(ctx, itemId, ownershipId)
	return err
}

// EditItemOwners converts echo context to params.
func (w *ServerInterfaceWrapper) EditItemOwners(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// ------------- Path parameter "ownershipId" -------------
	var ownershipId OwnershipIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "ownershipId", ctx.Param("ownershipId"), &ownershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ownershipId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.EditItemOwners(ctx, itemId, ownershipId)
	return err
}

// PostBorrow converts echo context to params.
func (w *ServerInterfaceWrapper) PostBorrow(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// ------------- Path parameter "ownershipId" -------------
	var ownershipId OwnershipIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "ownershipId", ctx.Param("ownershipId"), &ownershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ownershipId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostBorrow(ctx, itemId, ownershipId)
	return err
}

// GetBorrowingById converts echo context to params.
func (w *ServerInterfaceWrapper) GetBorrowingById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// ------------- Path parameter "ownershipId" -------------
	var ownershipId OwnershipIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "ownershipId", ctx.Param("ownershipId"), &ownershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ownershipId: %s", err))
	}

	// ------------- Path parameter "borrowingId" -------------
	var borrowingId BorrowingIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "borrowingId", ctx.Param("borrowingId"), &borrowingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter borrowingId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBorrowingById(ctx, itemId, ownershipId, borrowingId)
	return err
}

// PostBorrowReply converts echo context to params.
func (w *ServerInterfaceWrapper) PostBorrowReply(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// ------------- Path parameter "ownershipId" -------------
	var ownershipId OwnershipIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "ownershipId", ctx.Param("ownershipId"), &ownershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ownershipId: %s", err))
	}

	// ------------- Path parameter "borrowingId" -------------
	var borrowingId BorrowingIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "borrowingId", ctx.Param("borrowingId"), &borrowingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter borrowingId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostBorrowReply(ctx, itemId, ownershipId, borrowingId)
	return err
}

// PostReturn converts echo context to params.
func (w *ServerInterfaceWrapper) PostReturn(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "itemId" -------------
	var itemId ItemIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", ctx.Param("itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter itemId: %s", err))
	}

	// ------------- Path parameter "ownershipId" -------------
	var ownershipId OwnershipIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "ownershipId", ctx.Param("ownershipId"), &ownershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ownershipId: %s", err))
	}

	// ------------- Path parameter "borrowingId" -------------
	var borrowingId BorrowingIdInPath

	err = runtime.BindStyledParameterWithOptions("simple", "borrowingId", ctx.Param("borrowingId"), &borrowingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter borrowingId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostReturn(ctx, itemId, ownershipId, borrowingId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/items", wrapper.GetItems, options.OperationMiddlewares["getItems"]...)
	router.POST(options.BaseURL+"/items", wrapper.PostItem, options.OperationMiddlewares["postItem"]...)
	router.DELETE(options.BaseURL+"/items/:itemId", wrapper.DeleteItem, options.OperationMiddlewares["deleteItem"]...)
	router.GET(options.BaseURL+"/items/:itemId", wrapper.GetItem, options.OperationMiddlewares["getItem"]...)
	router.PATCH(options.BaseURL+"/items/:itemId", wrapper.EditItem, options.OperationMiddlewares["editItem"]...)
	router.POST(options.BaseURL+"/items/:itemId/comments", wrapper.PostComment, options.OperationMiddlewares["postComment"]...)
	router.POST(options.BaseURL+"/items/:itemId/owners", wrapper.PostItemOwners, options.OperationMiddlewares["postItemOwners"]...)
	router.DELETE(options.BaseURL+"/items/:itemId/owners/:ownershipId", wrapper.DeleteItemOwners, options.OperationMiddlewares["deleteItemOwners"]...)
	router.PATCH(options.BaseURL+"/items/:itemId/owners/:ownershipId", wrapper.EditItemOwners, options.OperationMiddlewares["editItemOwners"]...)
	router.POST(options.BaseURL+"/items/:itemId/borrowing/equipment", wrapper.PostBorrowEquipment, options.OperationMiddlewares["postBorrowEquipment"]...)
	router.POST(options.BaseURL+"/items/:itemId/borrowing/equipment/:borrowingId/return", wrapper.PostBorrowEquipmentReturn, options.OperationMiddlewares["postBorrowEquipmentReturn"]...)
	router.POST(options.BaseURL+"/items/:itemId/owners/:ownershipId/borrowings", wrapper.PostBorrow, options.OperationMiddlewares["postBorrow"]...)
	router.GET(options.BaseURL+"/items/:itemId/owners/:ownershipId/borrowings/:borrowingId", wrapper.GetBorrowingById, options.OperationMiddlewares["getBorrowingById"]...)
	router.POST(options.BaseURL+"/items/:itemId/owners/:ownershipId/borrowings/:borrowingId/reply", wrapper.PostBorrowReply, options.OperationMiddlewares["postBorrowReply"]...)
	router.POST(options.BaseURL+"/items/:itemId/owners/:ownershipId/borrowings/:borrowingId/return", wrapper.PostReturn, options.OperationMiddlewares["postReturn"]...)
	router.DELETE(options.BaseURL+"/items/:itemId/likes", wrapper.RemoveLike, options.OperationMiddlewares["removeLike"]...)
	router.POST(options.BaseURL+"/items/:itemId/likes", wrapper.AddLike, options.OperationMiddlewares["addLike"]...)
	router.POST(options.BaseURL+"/files", wrapper.PostFile, options.OperationMiddlewares["postFile"]...)
	router.GET(options.BaseURL+"/files/:fileId", wrapper.GetFile, options.OperationMiddlewares["getFile"]...)

}
