// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcW1Mbx5f/Kq7ZfUiqBBLY9Y9DVR58+W+K3WTNepOXTVFbg9TA2JJGnhk5piiqpkeY",
	"m4SFMRfL4BgbDAKMTGxiEy7mu7g1I+kpX2Gre0aa++gKxlm/uLA0fa6/Pn3O6TMapoJsJMZGQVTgqa5h",
	"KkZzdAQIgCP/62M5jv2ViQ50h7qjPbQwiD8MAT7IMTGBYaNUF6VMisrypJLd7L5O+SgGfxTDD/qoKB0B",
	"VJeRBuWjOHAnznAgRHUJXBz4KD44CCI0JisMxfDjTFQAA4CjRkZ8VD8TBu6cUWIeSc+RtIYS227MVQr1",
	"8mUEEPHgK70gTMdQYsWNr0qhXr7sr1HA8YNMrAlzG2jUy16gPfyMv3RhSdbVx2yk/K0BZjdBLDxEMMix",
	"McAJDCBf0lH+V8Dhv8A9OhILE45cHFC+Mtk+lg0DOkqN+DCYIyAqmJ/u9HcGENwuJbJybg3B7cJxDsFp",
	"BD8gmNGp8ALHRAeIIXRFfimz10n3VlawfbdAUMBsywrciQNesKugft0dvRaO991k2UiNyoTi4DotAIsy",
	"gc5LbYHOto5/UD6qn+UitEB1USH8nE0VH5GD5S0kils7CJ4g+AzBJIKr2h/SJBKlquYoy+SzK1XVMP+8",
	"E2diZfe0xEJBNm5xdofPBra/lSGFOBe1m08A9yyYR1BC0hSCKQSzCI4hOIfgAoKjBPWLWFJRKj19Ucgc",
	"G2TfqGVDEF7uIuIl52gDMKHq8Gi5bxkcDet0sCFymW0X5AAtgNAVa1ALdHzbFvimrfPyT52dXYFAVyDw",
	"P1aDtAlMBJDATIduRHFwVQOzzUohEAZN8ojGw2G6Dy9TeVTlafeMyxKDp/CxSs6EcPhGP9X1yzD1rxzo",
	"p7qof/HraYxfO1n8+On/jkciNDdEjfRa6VfO+frFsG83eTdd3HpVmJxA8LW8li58eIBgTj5JFGbGlHRa",
	"HsvgnShNIJhW0mkCpBSC62Q/riMRKo9XCnOHeLk0W1xdlnMpBDNISiJJQjCH4DaCWwSEZImURKKENzje",
	"2ilylGWLG6vFrVcIriD4EG9kScIAlsT8h+eyuIbgaxIQkghmFfFpOQ5kHMHso+Kx0KlDLs4DzmJ7iv+2",
	"+kqnrVbJtjSiGlA0R/kMW8iomxH2TjsS54727ajCtkom6h1v4lzYm8bPN38wEqH8dIzxY3F4f0dtwQez",
	"cNKJ4a+y7G3vnLaQzckTLy8oy6/IibCF4KhfWX6FGTMCkUej4hSyGd50ylflIovJ/MGBmtX6ZSkjP4Im",
	"Rjo1R251x4MelhdAiBrxDVNsFGiLLAG3nFTYPUe++pG+55JAG92gUjEs6cU8zZwqubqKLAFEyB9eOlSW",
	"kDikikBzHD1kE8BAvBdHP6uS5LipnXH5fBpx3aGaGKSOqJ2uQA9Up2lNQTADn66DHem9GjiuA4FmwvVB",
	"xBMcAkdHeTqIAW1Gem3K6qv1xdUc6czSAU7GBxsRqS5JnEAVZm4D/urQz7zWPqgIYAnxtsOgLu8TLh4+",
	"x1vctRQLsiFLovftN5cvBS51BDr/cSlw0Uk4hyIjEHAsM4zBzsiitP1YWXneIf+5h7OCtTQSobw/Vtp+",
	"/NfRBIKH5NRO/nU0ieDr0tIL+e07NdWUc+/k8QOcrotQefp7/uAVzgSk0XImMK2l8eKqsviylJlG0lTh",
	"3ROcAEjJ0lIWwVx+fweJsLT0sLifRvANJiVBBNOlxHH+6AmCucLkeOnJfRznyyIh+Dq/P62IT4s7uwhu",
	"FRPH8tQSkmaVFERwTd59KL98ixKHpcxxMb1M5H+D4BYRflsePyBkx3B+IqYQ3EFwHIkwfzilaqRk9nDm",
	"gxObCSROkzTmKcmFXhdeTpD8pJzAiLCweYD5qksIceXpSyQlsTz4MZyTfxTnP4rzSJTktU1ZzCCYK26d",
	"yLMpBFOFpKSnTDCtZKT84So2oAhLMCk/PEZwu3ByKB+NIjivSoW1wz7KamrCVHF8C+f8MFeYe4bgtLLw",
	"J5JmkZgqwX1l6jesAsnTCpObxa3fsC/m3xfeZ/E5l0iixHOUOELSe5TYQIm3ao6HxAfy2qayu4iRsDOD",
	"xDRO8ESoLOwqf7wvbq0UllYLT1eL41vFg20EU/Kz94WdMbVkkx88yx8vq6mmS+bGRAZ+LmcX/XQ8jNMy",
	"UyoxKAgxvsvvD7J3AdfOxkC0L9R+K+Y37YL2W7EBR+qV7MEzhqpPked/4uhYt3ZIe68xxUO1sWRPsC8Y",
	"beckoe3osT/hFVoIX5PcPj3ZMW7viqUdkyw9zzjT+NOCSvEsKkMHHl/i5pe4+WnjZg1toi+xtb7Y2pI+",
	"Qg21bv1Bu9GOgLGhVH9JYekj8D8wt4EZdp6dM0PZizPga/hU4OvtXTmk0hohX0Ui58yalJNO51lNHfhz",
	"ejQ1FAeIJbpreJADUYHWjj6bl+1ebf1u8eiy1bCvynoa2moGjXx6h6OhvaQ3MlxabPV3hhtp5UZAhLXe",
	"nEyRtusikqbJEZgjbbBlBN+Qluoj8t80OUrnERx1rmfr8ryxBq+vXG/Gv/auqcm9xDJOnouxvHDN7bbi",
	"790ar/UqDJvohjvA7aA7LWQ1iI86ESHQDnd+bnlGVeZkoSMb8zaxHESDIHibjQv/G2ryxvDvet8WioOm",
	"bcM0FGF5nh6wsvV3fGMYydhAcKr4Zp+k64tugxmm+Zj65YjFuSZveTEXIc5Ff3TSCMEnhEDWgaS2szMk",
	"zO1oEcpwO//XEXTn1rTTeIEW4rz9NibwHUpsIek1krJI+hMlJpT9CSy5CDu+U52hVtFqMdz5XfFkTp7e",
	"qzx00fSQkpyVZ9YtV1/VnfK53TSap6sqYVIzsQ52K1QM289nCVVmPzeaTjneLPy/mSX4VLGt0ayzdbHo",
	"S3T4Eh2qRQcy0hrtZ9V6PSrQQUFP0HDk6NEmBvQW1gAjDMb72oNsBFccPQIjgOCgv49l/6vt7kVbz5bS",
	"vkDSHyhxhBIz+F+Yu9LTrZ17KoK1S/0yFR91F3C8SuBie6A9QI74GIjSMabykY/MmhJ8qhMQJKix6tUe",
	"Dm00FgE7kOpheeHfmDDQJlEBL1xlQ0NlpbV4GImHBSZGc4Ifw6UtRAtkQFUfVTUHzPIMiFndiz9eJUnK",
	"BoK5f+/53neh5z+/N85vGMHYx0Rpbsgh6R0xQ0gbSeIAH2OjvMq9M9BhEZ+OxcJMkOjsv8WrebAuu1fh",
	"SDQhPM263PgPbPZLgYBdzfz+tLKziusrcyTQnUrmeMsNMaowdygn0kZDIGmW9HQTKLGIEjsEHJOVFE+D",
	"BWkr/kKp3u3FJLVZl2F1ensESzYAHDz+PdAdbjJbwGI2JkIPAP+tGBgwG6wGL7nZ65L3CA+CKXnnsbyc",
	"LWu7hLPAGk2WEJG0jhJvazWZzzS279KP1B/xm+bqSXfPX2nquhm6mzxg42SZTk+Ny7kn2oBpYp208d+p",
	"wUAd8am0/eVHML8vFtc3kDQrpxfkD4sWHcmc+Z04IF7RQpUeUa2T5XpUtookz0wXNnYRTOFaY2IMMx3f",
	"a04MHtBccLA+MTwsI4vPSDGgNTAalUot1es0jk78GYKj+cN3yvwuubSqSKsxtYUAvER7Hqbk+9lSglyc",
	"aRQmkDQlrz1BcFRe2ZNnSO+n8oyqmtq5wYp76xVmIoxAeb+6UEUvlBgnBj9BMFdaSMobSXllT5kUT0nT",
	"wuYBZnR/Wp5YRDBVPJkz3Dx6K8v29/OgXm0dJcbaSrukRbamNdOagpdAD5jEqv2GvZXiljJr8tqCsUng",
	"ImsbuBcMx0OgRTLnj+cRzBXXYWFvhfQQj0lgntB6kTDpFipYTugb8tyUvVVPL+9Dv6YpL9MotE3depIC",
	"m/dS5TSBvD1gOd6I9/Q974K38nmmqtKrNVCdMzztgs89w2uRtYxTZI4Wa23qVpdcZIC1qhOvqaVCzZ5M",
	"LOM4Ka1aXEqSFkziosPbaNnNUmaG9LGkcijHiY4zDKRZZWGXuD5dyByWUm+qwKCSl/iH1UJ7RJUAVzp2",
	"cFwnn1fgYd9RtedxhjFlxzzOTT15cqqUWasKbq8Ui2oyGlSDjzYQW2di25hBYK64+bawt6sk7ssrv9ex",
	"+etKZk0va5KZVFoIDtoN/M8Q02zwqCtm1BIjWuvbJiN5tf3fSmDokFibVJb26g4E/srLZn5ganc2CR3X",
	"Y+cq4Wd8G+E0QOTyuuQZtwq8pDjdI6YFEFPfIcHI0soqO6xU/WoHlp/TX7s8I3xpL3qeLsoIi0+ELZ33",
	"54MoUsgt1o0o46s2p4af8kDG6SDGOPJxxoAJGtmee6wg6S0ZX32L+ZF8t7iezh8vKxMzLtDRX2Jywo76",
	"rosp67UICDNEi23thyHI/Uth6p1yP4lgTmtJiBAbIbGJEkdfXQoEvnbEshlTN0GEvQt+YG6DmrJpZWdV",
	"3t9HcNucAuPKvsH2sqtLyh0bMnsMnzWcgpAuwyiCO2piiqQp5d2Ei5O0V45akJtqG9jFibpMWI5yC6R5",
	"b14JhZxd2eHhSrMw59ub20ZvkhbSQy8/Ouw09e6uhTHaYp7DhaJ4v9IHV7KbODw8ms4fL6s9pEr3sFJT",
	"yyf3i+vQeIPm3A1RB81OMfLrk2xnHPtZM2OP6F9Hb+J06hniVexhvBmP5akVl0iiwcwDgv5hwzXyiFfs",
	"PwVM6U0UA6pqbaWcJydYWjFOHmgumPuqPm//NSdTd+LUfVlueJy3+BA4m/hwHlFZeJ8tLY0ZQ8NX+tcw",
	"W8g9L8yMqThA8OTrJuKGXsc2faY1jPQqxe5Z9FDOGpEOzM9zP8746xuFyU31Hb1y44TcnIrTCGaV0XRx",
	"PVl8nlUeP2ikAq4CUP+w4TcCPac9rpafuzqkjaefqh+rjICcVx+aHAiz5N+x4jpUlpccm/AXvvq4mPy4",
	"mFQWX+IKzuR+aPyKlBmZ/MEETtlFSN682PzaEQWf4HCtvsj+c5aG4ZcG4ernKj9b+HkoXD0wqz/EeLrR",
	"GXP4RLG5wvrz2tWGjfgBwQ2vTQ635ddqvb5ePJkr7MydetBuUYv8nGyDc9Z99yi5zitYa2qVYxqAu+s8",
	"Shjj2FA8qL23bR5O7mPZO213L7YLHB1rvxXz0zGGso/s8AI9gA9wx9UhcLdMQWDayXCzM5UwGyRDdTqN",
	"Lr+ffDjI8kLX5cDlgLqyt6KilUSlR1VaeKHWcld6us0/Fcw7cDa1kt0WV7rH9vUOjU43KmpbzIOEoUhx",
	"IaHVJ640KlmJlESJeW2w1Y1YGSMO1NR5WYeZYhdS6ojsSO/I/wUAAP//8BCv6elaAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
