// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FzbUxvHmv9XUrP7kFQJJLDrJKEqD7F9NsXuyZr1nrxsitoapAbGljTyzMgxRalqeoS5SVjY5mIZfIwN",
	"BgFGcGxiEzDmf3FrRtJT/oWt7hlp7iMNQphk/ZIYafq79Hfp7/v1NxqlwmwswcZBXOCpnlEqQXN0DAiA",
	"I38NsBzH/sLEh3ojvfE+WhjGH0YAH+aYhMCwcaqHqrw+kCcOe69RAYrBfyfwUwEqTscA1WMkQAUoDtxO",
	"MhyIUD0ClwQBig8PgxiNaQojCfw4ExfAEOCoVCpADTJR4M4WpeeR9BxJayi97cZcpeCXLyOAmAdf6QVh",
	"Oo7SK258VQp++bK/xAHHDzMJd+bKlKgsTymFTTfOBhp+2Qu0h5Hxly4syTp/zFK1bw0+dgMkoiP4zwTH",
	"JgAnMIB8Scf5XwCH/wXu0rFElHDkkoAK1MgOsGwU0HEqFcCeHANxwfx0d7A7hOB2NV2Qi2sIbpePiwjO",
	"IPgBwbxOhRc4Jj5ENkJX5Ocae510f30FO3AThAXMtqbA7STgBbsK6te98avR5MANlo01qUwkCa7RArAo",
	"E+q+3BHq7uj6CxWgBlkuRgtUDxWhBQONmioBIgfLW0hUtnYQPEHwGYIZBFe1f0hTSJQabkdNpoBdqYYb",
	"89fbSSZRM8+Z7FCYTVqM3RWwOdufaiOFJBe3b58A7lp8HkEJSdMIZhEsIDiO4ByCCwiOEa9fxJKKUvXp",
	"i3L+2CD7RjMBQXi5i4iXXKAAYCKN3ePMbctEKF34Jg1syFzmvQtzgBZA5HtrUgt1fdsR+rqj+5u/d3f3",
	"hEI9odD/WDekQ2BigCRmOnI9jpOrmphtuxQBUdAij3gyGqUHoqDGoyFPu2VclhgshY9VvIqORq8PUj0/",
	"j1L/yoFBqof6l6BewwS1kyWIn/7vZCxGcyNUqt9Kv37O+xfDHm7yXq6y9ao8NYngrryWK3+4j2BRPkmX",
	"Z8eVXE4ez+NIlCYRzCm5HHGkLILrJB7XkQiVxyvluSO8XHpYWV2Wi1kE80jKIElCsIjgNoJbxAnJEimD",
	"RAkHOA7tLDnKCpWN1crWKwRXEHyAA1mSsANLYunDc1lcQ3CXJIQMggVFfFrLA3lHZw5QyUSk7S6X5AFn",
	"2XuK/7bxSqdQq1dbGlH1E0ozVMAQQkbdjG7vFJG4drSHIxOx10a2StQ73yS5qDeNn278zUiECtIJJojF",
	"4YNdzSUfzMJJJ4a/wrK3vGvacqEoT778Qll+RU6ELQTHgsryK8yYEYg8GhWnlM3wplO+IRdZzJQOD9Wq",
	"NihLefkRNDHSqTly850P+lheABEqFRil2DjQFlkSbq2osFuOfPUjfdelgDaaQaViWNKfClg51Wt18hcW",
	"j/zDS4f6EpKHVBFojqNHbAIYiPfj7GdVkhw3zTPWFlAp1wjVxCB9RPN0BXqoMU2LaoRBQNfB7un9mnNc",
	"AwLNRP25iKdzCBwd5+kwdmizpzenrL5aX9zIkM4sHdzJ+OBpRPIliZNTRZlbgL8y8hMPOLMAlhRvOwx8",
	"WZ9w8bA5DnHXVizMRiyF3rdff3M5dLkr1P2Xy6FLTsI5NBmhkGObYUx2RhbV7cfKyvMu+bd9XBWs5ZAI",
	"5YPx6vbj399PInhETu3M7++nENytLr2Q37xVS025+FaeOMTlugiVp/8sHb7ClYA0VqsEZrQyXlxVFl9W",
	"8zNImi6/fYILAClTXSogWCwd7CARVpceVA5yCL7GpCSIYK6aPi69f4JgsTw1UX1yD+f5mkgI7pYOZhTx",
	"aWVnD8GtSvpYnl5C0kMlCxFck/ceyC/foPRRNX9cyS0T+V8juEWE35YnDgnZcVyfiFkEdxCcQCIsHU2r",
	"Gin5fVz54MJmEokz+DH4FH8Cd8svJ/Hn9QJGhOXNQ8xXXUKIK09fIimD5YErak3+UZz/KM4jUZLXNmUx",
	"j2CxsnUiP8wimC1nJL1kgjklL5WOVvEGirAKM/KDY4wEnBzJ78cQnFelwtphGxU0NWG2MrGFa35YLM89",
	"Q3BGWfgNSQ+RmK3CA2X6H1gFUqeVpzYrW//Atph/V35XwOdcOoPSz1H6PZLeofQGSr9Razwk3pfXNpW9",
	"RewJO7NIzOECT4TKwp7y67vK1kp5abX8dLUysVU53EYwKz97V94ZV1s2+f6z0vGyWmq6VG5MbOinWnUx",
	"SCejAtVDmUqJYUFI8D3BYJi9A7hONgHiA5HOm4mgKQo6byaGHKnXqwfPHKo+RZ7/O0cnerVD2nuNKR+q",
	"wJK9wP7CuHdOEtqOHvsTXqmF8DXJHdCLHWN413fascjS64xzzT9n0CmeR2fowONz3vycNz9t3mwCJvqc",
	"W/3l1jPBEZrodf0n7dMiAkZAyX9LYcER+L8xt4DZ7TyRM0Pbiyvgq/hU4P1iVw6ltEYoUJfIubIm7aTT",
	"edYUAn9Bj6ZT5QGyE71NPMiBuEBrR5/Nynarnn20eKBsTcRVTU8DrGbQKKAjHKeKJR3IcIHY/CPDp4Fy",
	"YyDGWm9OpgnsuoikGXIEFgkMtozgawKpPiJ/5shROo/gmHM/68vyxh7cX7vein3tqKnJvGRnnCyXYHnh",
	"qtttxZ8bGm/2Kgxv0XV3B7c7Xbs865T+4dMjMIZnU9KtzmjInCx0ZGMOE8tBNAzCt9ik8L+RFm8M/6z3",
	"bZEkaHlvmFNlWJ6nh6xsg11fG0YyNhCcrrw+IOX6ottghmk+xr8ciSTX4i0v5oLv33900gjBJ4RAwYGk",
	"Ftl5kuZ2tAxluJ3//T1059ay0XiBFpK8/TYm9B1KbyFpF0kFJP2G0pPKwSSWXIRd36nGULtotRnu/q5y",
	"MifP7NcfumR6SMk8lGfXqYBPo/zRbhrN01X1NKltse7sVlcxhF/AkqrMdj5tOeV4s/D/ZpbgU+W201ad",
	"Z5eLPmeHz9mhUXbAsjLxQVbt1+MCHRb0Ag1njj5tYkCHsIYYYTg50BlmY7jj6BMYAYSHgwMs+18ddy7Z",
	"MFtK+wJJv2LkLj2L/wuL3/f1aueeKBku9WtUAtQdwPEqgUudoc4QOeITIE4nmPpHATJrSvxTnYDA/8Ll",
	"Nf4/Tm00FgEbkMKQ+78xUaBNogJeuMJGRmpKa/kwlowKTILmhCB2l44ILZABVX1U1ZwwazMgZnUv/XiF",
	"FCkbCBb/ve+HwBd9//mDcX7D6IwDTBzDRXb/SZldSBtJ4gCfYOO8yr071GURn04kokyY6By8ybNxs+xe",
	"jSPRhPA063L9P/C2Xw6F7GpiPHtnFfdX5kygGxWT42uAGFWeO5LTOeNGYNAXY7pplF5E6R3iHFP1Ek9z",
	"CwIr/kyp1u3HJLVZl1F1ejuFJRsCDhb/AegGN21byLJtTIweAsGbCTBk3rAmrOS2X5e9R3gwBL3zWF4u",
	"1LRdwlVgk1uWFpG0jtJvmt2ygGlm3wWP1B8JmubqCboXrIO6bhvdSx6wcbJMp2cn5OITbcA0vU5g/Ldq",
	"MlBHfOqwv/wIlg7EyvoGkh7KuQX5w6JFRzJnfjsJiFW0VKVnVOtkuZ6VrSLJszPljT0Es7jXmBzHTCf2",
	"WxODBzQXHvYnhsfOyOIz0gxoAMZppVJbdZ+boxN/huBY6eitMr9HLq3q0mpMbSkAL9Geh1n5XqGaJhdn",
	"GoVJJE3La08QHJNX9uVZgv3Un1FVU5EbabrOwkWvKBNjBMr71YUGeqH0BNnwEwSL1YWMvJGRV/aVKbFN",
	"muILOFis3puRJxfxXdjJnOHm0VtZdnCQB361dZQYayvtEYhsTQPTWnIvjPEYxWr+hv0sxa3m1+S1BSNI",
	"4CJrB7gbjiYj4IxkLh3P4zvSdVjeXyEY4jFJzJMaFgkzbqmC5YSBEc+g7G94enkf+k1NeZlGoW3q+ikK",
	"bNbL1soE8vaA5Xgj1tNj3sXfaueZqkq/BqA6V3jaBZ97hXdGu2WcInPcsbMt3XzJBSLOIpktdVVtFZq2",
	"ZHoZ50lp1WJSUrRgEpfsJJTCZjU/S3AsqZbKcaHj7AbSQ2Vhj5g+V84fVbOvG7hBvS4JjqqNdkqVAHc6",
	"due4Rj6vu4c9opqv4wxjyo51nJt68tR0Nb/W0Lm9SiyqxWzQyH20gVifhe3pNgQWK5tvyvt7SvqevPJP",
	"H8Hvq5g1vaxJZlJpITxs3+C/RphWk4evnNFMjjhb27aYyRvF/1k6hu4Sa1PK0r7vRBCsv2wWBCa4s0XX",
	"cT12rhB+xrcR2uFELq9LnjNU4CVFe4+YM3Ax9R0S7FlaW2V3K1W/5h0rOGp4hz0V5PSXMFvwtkDD5+1v",
	"3vtyUe1d0fY6KmHxidxT533udU/paAG3KuY+Xv0ZBAR3VSicUJkxuKmLg9eWGV17i7RAGTz+oPWnZNIS",
	"PjNHQ53lRm2KYbphWJBudNF3WBjfF2pbkq1NlbTHZ41zK+fssmEj2wufQpH0hszgvsH8SNFeWc+VjpeV",
	"yVkX19HfxHLyHfWFHVPpbhEQ5okW29qvW5BLpPL0W+VeBuNjKq4iQrwJ6U2Ufv/l5VDoK0dfNvvUDRBj",
	"7wA81dhUS6DsrMoHB3hk2lTHY3jilBi5q0k8w9pHHUXyxBgeKiDVNZKmlbeTLkbS3ptKBc4qgF2MqMsE",
	"F3Ucp3Vrfh+JOJuyy8OUZmEutjW3jdYkONgDLzs6RJp6AXmGOdp27FXEe3UwXyls4vTwaKZ0vKwCYXUI",
	"tA4MyCf3KuvQeA3oDOmo03JtzPz6ON45537WzNgj+/sAWNrTlBGrYgvjYDyWp1dcMonmZh4uGBw13IWn",
	"vHJ/G3xKR4IMXtUsHnSRjGDBk5wsEGhzE2L/SSoTxNJ2W9ZQm4uWH0Lnkx8uoleW3xWqS+PG1PCl/jUs",
	"lIvPy7Pjqh8gePJVC3lDb4H59rfbLp7eoN0+DyDovD3SgflFBhWNPyFSntpUXzSsoT/k+he/blhQxnKV",
	"9UzleUF5fP80HXADBzWDRF6TFFdqz10Z0Wbs22rHBnMsF9WGJgPiKekxBMcr61BZXnK8Sfjiy4+LmY+L",
	"GWXxJe7gTOaHxq9Im5EvHU7ikl2EBGzZ/MrRCz7B4Xo6WLBVdw1y9d9e/GMo3Dgxq78m2d7sjDl8otxc",
	"Z/3HimpDIOL5Sa8gh9vyrtqvr1dO5so7c21P2ueG7J9LGFww/N+j5bqoztoUVI5pAO6O8zxkgmMjSfWF",
	"NeuE9QDL3u64c6lT4OgE/pEAOsFQ9rkjXqCH8AHuuDoC7tQoCEwnmdB2phJlw3TURKMnGCQfDrO80PNN",
	"6JuQurK/rqKVRB2jqi68UHu57/t6zb93zDtwNkHJbovr6HEq4MbWAHS6UVFhMQ8ShibFhYTWn7jSqFcl",
	"UgaP7KrTuW7Eaj7iQE0d+nUYjHYhpc75pvpT/zcA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
