// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FzbUxvHmv9XUrP7kFQJJDB7klCVhzg5m2L3ZMNmT142RW0NUgPjSBp5ZuSEolQ1PcLcJCJsc7EMHLDB",
	"IMAIjs2xMRjzv7g1I+kp/8JW94w095EGIUxy/JIYafq79Hfp7/v1NxqjwmwswcZBXOCp3jEqQXN0DAiA",
	"I38NshzH/szEh/siffF+WhjBH0YAH+aYhMCwcaqXqjw/lidP+r6mAhSD/07gpwJUnI4BqtdIgApQHLid",
	"ZDgQoXoFLgkCFB8eATEa0xRGE/hxJi6AYcBRqVSAGmKiwJ0tSi8g6TGSNlF6z425SsEvX0YAMQ++0hPC",
	"dAKl1934qhT88mV/jgOOH2ES7syVaVFZmVYKO26cDTT8shdoDyPjL11YknX+mKVq3xp87HuQiI7iPxMc",
	"mwCcwADyJR3nfwYc/hf4hY4looQjlwRUoEZ2kGWjgI5TqQD25BiIC+anu4PdIQT3qumCXNxEcK98VkRw",
	"FsG3COZ1KrzAMfFhshG6Ij/W2OukB+or2MFbICxgtjUFbicBL9hVUL/ui38VTQ5+z7KxJpWJJMHXtAAs",
	"yoS6ezpC3R1df6IC1BDLxWiB6qUitGCgUVMlQORgeQuJyu4+gucIriGYQXBD+4c0jUSp4XbUZArYlWq4",
	"MX++nWQSNfNcyg6F2aTF2F0Bm7P9oTZSSHJx+/YJ4BeLzyMoIWkGwSyCBQQnEJxHcBHBceL1S1hSUaqu",
	"PinnzwyybzcTEISXu4h4yTUKACbS2D0u3bZMhNKFb9LAhsxl3rswB2gBRL60JrVQ1+cdoU87uj/7a3d3",
	"byjUGwr9r3VDOgQmBkhipiPfxXFyVROzbZciIApa5BFPRqP0YBTUeDTkabeMyxKDpfCxilfR0eh3Q1Tv",
	"j2PUv3JgiOql/iWo1zBB7WQJ4qf/JxmL0dwolRqw0q+f8/7FsIebfJir7D4rT08heCBv5spvf0WwKJ+n",
	"y3MTSi4nT+RxJEpTCOaUXI44UhbBLRKPW0iEysP18vwpXi7dr2ysyMUsgnkkZZAkIVhEcA/BXeKEZImU",
	"QaKEAxyHdpYcZYXK9kZl9xmC6wjew4EsSdiBJbH09rEsbiJ4QBJCBsGCIq7W8kDe0ZkDVDIRabvLJXnA",
	"Wfae4j9vvNIp1OrVlkZU/YTSDBUwhJBRN6PbO0Ukrh3t4chE7LWRrRL1zjdJLupN44fv/2IkQgXpBBPE",
	"4vDBruaSD2bhpBPD32TZn7xr2nKhKE89/UhZeUZOhF0Ex4PKyjPMmBGIPBoVp5TN8KZTviEXWcyUTk7U",
	"qjYoS3n5ATQx0qk5cvOdD/pZXgARKhUYo9g40BZZEm6tqLBbjnz1Lf2LSwFtNINKxbBkIBWwcqrX6uQv",
	"LB75h5cO9SUkD6ki0BxHj9oEMBAfwNnPqiQ5bppnrC2gUq4RqolB+ojm6Qr0cGOaFtUIg4Cug93TBzTn",
	"+BoINBP15yKeziFwdJynw9ihzZ7enLL6an1xI0M6s3RwJ+ODFxHJlyROThVlfgL8zdEfeMCZBbCkeNth",
	"4Mv6hIuHzXGIu7ZiYTZiKfQ+//SznlBPV6j7Tz2hG07COTQZoZBjm2FMdkYW1b2HyvrjLvn1Ea4KNnNI",
	"hPLxRHXv4W9vphA8Jad25rc30wgeVJefyC9eqqWmXHwpT57gcl2EyurfSyfPcCUgjdcqgVmtjBc3lKWn",
	"1fwskmbKLx/hAkDKVJcLCBZLx/tIhNXle5XjHILPMSkJIpirps9Kbx4hWCxPT1Yf3cV5viYSggel41lF",
	"XK3sHyK4W0mfyTPLSLqvZCGCm/LhPfnpC5Q+rebPKrkVIv9zBHeJ8Hvy5AkhO4HrEzGL4D6Ck0iEpdMZ",
	"VSMlf4QrH1zYTCFxFj8GV/En8KD8dAp/Xi9gRFjeOcF81SWEuLL6FEkZLA9cV2vyd+LCO3EBiZK8uSOL",
	"eQSLld1z+X4WwWw5I+klE8wpeal0uoE3UIRVmJHvnWEk4PxUfjOO4IIqFdYO26igqQmzlcldXPPDYnl+",
	"DcFZZfE1ku4jMVuFx8rM37AKpE4rT+9Udv+GbbHwqvyqgM+5dAalH6P0GyS9QultlH6h1nhI/FXe3FEO",
	"l7An7M8hMYcLPBEqi4fKP15VdtfLyxvl1Y3K5G7lZA/BrLz2qrw/obZs8q9rpbMVtdR0qdyY2PAPtepi",
	"iE5GBaqXMpUSI4KQ4HuDwTB7B3CdbALEByOdtxJBUxR03koMO1KvVw+eOVR9ijz/V45O9GmHtPcaUz5U",
	"gSV7gf2Rce+cJLQdPfYnvFIL4WuSO6AXO8bwru+0Y5Gl1xlXmn8uoVO8is7QgceHvPkhb77fvNkETPQh",
	"t/rLrZeCIzTR6/pP2hdFBIyAkv+WwoIj8H9hfgJmt/NEzgxtL66Av8KnAu8Xu3IopTVCgbpEzpU1aSed",
	"zrOmEPhrejRdKA+Qnehr4kEOxAVaO/psVrZb9fKjxQNlayKuanoaYDWDRgEd4bhQLOlAhgvE5h8ZvgiU",
	"GwMx1npzMkNg1yUkzZIjsEhgsBUEnxNI9QH5M0eO0gUEx537WV+WN/bg/tr1VuxrR01N5iU742S5BMsL",
	"X7ndVvyxofFmr8LwFn3n7uB2p2uXZ13QP3x6BMbwbEq61RkNmZOFjmzMYWI5iEZA+Cc2KfxfpMUbwz/q",
	"fVskCVreG+ZCGZbn6WEr22DXp4aRjG0EZyrPj0m5vuQ2mGGaj/EvRyLJtXjLi7ng+/dvnTRC8BEhUHAg",
	"qUV2nqS5fS1DGW7nf3sD3bm1bDReoIUkb7+NCX2B0rtIOkBSAUmvUXpKOZ7Ckouw6wvVGGoXrTbD3V9U",
	"zufl2aP6QzdMDymZ+/LcFhXwaZTf202jebqqnia1Ldad3eoqhvALWFKV2c4XLaccbxb+aWYJ3lduu2jV",
	"eXm56EN2+JAdGmUHLCsTH2LVfj0u0GFBL9Bw5ujXJgZ0CGuYEUaSg51hNoY7jn6BEUB4JDjIsv/dceeG",
	"DbOltC+Q9A+M3KXn8H9h8cv+Pu3cEyXDpX6NSoC6AzheJXCjM9QZIkd8AsTpBFP/KEBmTYl/qhMQ+F+4",
	"vMb/x6mNxiJgA1IYcv93Jgq0SVTACzfZyGhNaS0fxpJRgUnQnBDE7tIRoQUyoKqPqpoTZm0GxKzujW9v",
	"kiJlG8Hif/R/E/io/7++Mc5vGJ1xkIljuMjuPymzC2kjSRzgE2ycV7l3h7os4tOJRJQJE52Dt3g2bpbd",
	"q3EkmhCeZl2++0+87T2hkF1NjGfvb+D+ypwJdKOmAtS/hW54D7OUzlfl/YfKzlolfYbh5fHH8sxrAwmc",
	"g2qYGlWeP5XTOeNyjBtjWDiN0ksovU/8a7peJWqeRZDJHynVQQYwSW1cZkwdAE9hEYeBg9N8A3SfMe18",
	"yLLzTIweBsFbCTBs3vMmDO225T3eG4dR7P2H8kqhpu0yLiSvbtfTIpK2UPpFs7seML054IKK6o8ETdP9",
	"BGMM1qFlN1v1kQdsnCwz8tlJufhIG3NNb5HLhJdqSlIHjeqXD/IDWDoWK1vbSLov5xblt0sWHcm0++0k",
	"IIbVEqae163z7frZYBVJnpstbx8imMUdz9QEZjp51JoYPKC58Ig/MTx2RhbXSEuiwSgXlUoFDHxujk58",
	"DcHx0ulLZeGQXJ3VpdWY2hIRXqI9D7Py3UI1Ta7vNApTSJqRNx8hOC6vH8lzBIGqP6OqpuJH0kydhYte",
	"USbGCJT3CxQN9ELpSbLh5wgWq4sZeTsjrx8p02KbNMXXgLBYvTsrTy3hG7nzecP9p7ey7NAQD/xq6ygx",
	"1lY6JEDdpgbpteReGGkyitX8Pf9lilvNb8qbi0aowkXWDvBLOJqMgEuSuXS2gG9qt2D5aJ0gmWckMU9p",
	"iCjMuKUKlhMGRz2DcqDhAehdejQ1a2YayLap66c0sVkvWytW8AlnPd6I9fSYd/G32nmmqjKgwbjOdaZ2",
	"zeheZ17Sbhln2Rx37HILSF9ygYizSGZLfaU2LE1bMr2C86S0YTGpVvf0ONU9SmGnmp8jaJpUS+W4VnJ2",
	"A+m+snhITJ8r50+r2ecN3KBelwTH1HY/pUqA+y27c3xNPq+7hz2imi8FDcPSjqWgm3ry9Ew1v9nQub1K",
	"LKrFbNDIfbSxXJ+18cU2BBYrOy/KR4dK+q68/ncfwe+rmDW9MkomY2khPGLf4D9HmFaTh6+c0UyOuFzb",
	"tpjJG8X/ZTqG7hKb08ryke9EEKy/8hYEJtC1RddxPXZuEn7GdyLa4UQuL21eMWDhJUV7j5hLcDH1TRbs",
	"WVpbZXcrVb/mHSs4ZniTPhXk9FdBW/C2QMPn7e//+3JR7Y3V9joqYfGe3FPnfeV1T+l0Ebcq5j5e/TEG",
	"BA9UQJ5QmTW4qYuD15YZXXuXtEAZPISh9adk3hOumaOhznK7Nksx0zAsSDe65DssjG8ttS3J1mZb2uOz",
	"xumZK3bZsJHttU+hSHpBJoFfYH6kaK9s5UpnK8rUnIvr6O+DOfmO+tqQqXS3CAjzRIs97Tc2yFVWeeal",
	"cjeD8TEVVxEh3oT0Dkq/+bgnFPrE0ZfNPvU9iLF3AJ6tbKolUPY35ONjPLhtquMxPHFBpN7VJJ5h7aOO",
	"InliHI82kOoaSTPKyykXI2lvb6UClxXALkbUZYJLOo7TujW/jEScTdnlYUqzMNfbmntGaxIc7J6XHR0i",
	"Tb0GvcQcbTv2KuLdOpivFHZwengwWzpbUYGwOgRaBwbk87uVLWi8jHSGdNSZvTZmfn0o8IpzP2tm7JH9",
	"fQAs7WnKiFWxhXEwnskz6y6ZRHMzDxcMjhlu5FNeub8NPqUjQQavahYPuk5GsOBJThYItLkJsf8wlgli",
	"absta6jNdcsPoavJD9fRK8uvCtXlCWNq+Fj/GhbKxcfluQnVDxA8/6SFvKG3wHz7220XT2/Qbl8FEHTV",
	"HunA/DqDisYfMilP76ivO9bQH3L9i196LCjjucpWpvK4oDz89SIdcAMHNYNEXpMUN2vP3RzVJv3bascG",
	"ozDX1YYmA+JZ7XEEJypbUFlZdrxJ+Ojjd0uZd0sZZekp7uBM5ofGr0ibkS+dTOGSXYQEbNn5xNEL3sPh",
	"ejFYsFV3DXL1X4D8fSjcODGrv2nZ3uyMObyn3Fxn/fuKakMg4ilOryCHe/KB2q9vVc7ny/vzbU/aV4bs",
	"X0kYXDP836Pluq7O2hRUjmkA7o7zPGSCYyNJ9bU565z3IMve7rhzo1Pg6AT+qQI6wVD2uSNeoIfxAe64",
	"OgLu1CgITCeZE3emEmXDdNREozcYJB+OsLzQ+1nos5C6cqCuopVEHaOqLj5Re7kv+/vMv7rMO3A2Qclu",
	"i+vocSrgxtYAdLpRUWExDxKGJsWFhNafuNKoVyVSBo/sqtO5bsRqPuJATR36dZitdiGlzvmmBlL/PwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
